<?php /** @var \Magento\Catalog\Block\Product\ProductList\Item\AddTo\Compare $block */ ?>

<div class="d-flex justify-content-center align-items-center">
    <h4><?= __('Compare'); ?></h4>
    <a href="#"
       class="action tocompare"
       title="<?= __('Add to Compare'); ?>"
       aria-label="<?= __('Add to Compare'); ?>"
       data-post='<?= $block->getCompareHelper()->getPostDataParams($block->getProduct()); ?>'
       role="button">
        <span class="material-icons">compare_arrows</span>
    </a>
</div>
