<?php
declare(strict_types=1);

namespace Nextouch\Catalog\Model\Config\Product;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;
use Magento\Eav\Model\Entity\Attribute\Source\SourceInterface;
use Magento\Framework\Data\OptionSourceInterface;

class FastEstTypes extends AbstractSource implements SourceInterface, OptionSourceInterface
{
    public function getAllOptions(): array
    {
        $this->_options = [
            ['label' => 'Lavatrice', 'value' => 12],
            ['label' => 'Lavastoviglie', 'value' => 13],
            ['label' => 'Asciugatrice', 'value' => 14],
            ['label' => 'Frigo', 'value' => 15],
            ['label' => 'Sbs/coreano', 'value' => 16],
            ['label' => 'Piano Cottura', 'value' => 17],
            ['label' => 'Forno', 'value' => 18],
            ['label' => 'Cucina', 'value' => 19],
            ['label' => 'Altro', 'value' => 20],
            ['label' => 'Tapis roulant', 'value' => 21],
            ['label' => 'Cyclette', 'value' => 22],
            ['label' => 'Palestra', 'value' => 23],
            ['label' => 'Tavolo', 'value' => 24],
            ['label' => 'Congelatore', 'value' => 27],
            ['label' => 'Lista Nozze', 'value' => 29],
            ['label' => 'Televisore', 'value' => 30],
            ['label' => 'Televisore A Muro', 'value' => 31],
            ['label' => 'Kit Surround', 'value' => 32],
            ['label' => 'Lava Asciuga', 'value' => 33],
            ['label' => 'Clima Fisso Monosplit', 'value' => 34],
            ['label' => 'Clima Portatile', 'value' => 35],
            ['label' => 'Consegna A Cat', 'value' => 36],
            ['label' => 'Ritiro Presso Cat', 'value' => 37],
            ['label' => 'Ritiro Raee Cliente', 'value' => 38],
            ['label' => 'Ritiro Raee Negozio', 'value' => 39],
            ['label' => 'Exclusive', 'value' => 40],
            ['label' => 'Kit Giunzione Lv', 'value' => 41],
            ['label' => 'Ritiro Bancale Vuoto Da Negozio', 'value' => 42],
            ['label' => 'Articolo Omaggio/promozione/abbinato', 'value' => 43],
            ['label' => 'Sopralluogo Clima', 'value' => 44],
            ['label' => 'Clima Fisso Dualsplit', 'value' => 45],
            ['label' => 'Clima Fisso Trialsplit', 'value' => 46],
            ['label' => 'Macchine Foto', 'value' => 47],
            ['label' => 'Forno A Microonde', 'value' => 48],
            ['label' => 'Impianti Hi-fi', 'value' => 49],
            ['label' => 'Home Cinema', 'value' => 50],
            ['label' => 'Radio', 'value' => 51],
            ['label' => 'Radio Sveglia', 'value' => 52],
            ['label' => 'Stufa Elettrica', 'value' => 53],
            ['label' => 'Deumidificatore', 'value' => 54],
            ['label' => 'Ventilatore', 'value' => 55],
            ['label' => 'Videocamere', 'value' => 56],
            ['label' => 'Monitor', 'value' => 57],
            ['label' => 'Stampante', 'value' => 58],
            ['label' => 'Computer Fisso', 'value' => 59],
            ['label' => 'Computer Portatile', 'value' => 60],
            ['label' => 'Aspirapolvere', 'value' => 61],
            ['label' => 'Macchina Caffè', 'value' => 62],
            ['label' => 'Rasoio', 'value' => 63],
            ['label' => 'Ferro A Vapore', 'value' => 64],
            ['label' => 'Ferro A Caldaia', 'value' => 65],
            ['label' => 'Tostapane', 'value' => 66],
            ['label' => 'Friggitrice', 'value' => 67],
            ['label' => 'Frullatore', 'value' => 68],
            ['label' => 'Robot', 'value' => 69],
            ['label' => 'Tritatutto', 'value' => 70],
            ['label' => 'Spazzolino Elettrico', 'value' => 71],
            ['label' => 'Tagliacapelli', 'value' => 72],
            ['label' => 'Phon', 'value' => 73],
            ['label' => 'Macchina Cucire', 'value' => 74],
            ['label' => 'Telefono Cellulare', 'value' => 75],
            ['label' => 'Telefono Cordless', 'value' => 76],
            ['label' => 'Decoder Digitale', 'value' => 77],
            ['label' => 'Videoregistratore', 'value' => 78],
            ['label' => 'Macinacaffè', 'value' => 79],
            ['label' => 'Macchina Del Pane', 'value' => 80],
            ['label' => 'Scopa Elettrica', 'value' => 81],
            ['label' => 'Bilancia', 'value' => 82],
            ['label' => 'Lettore Mp4', 'value' => 83],
            ['label' => 'Console Videogiochi', 'value' => 84],
            ['label' => 'Netbook', 'value' => 85],
            ['label' => 'Spremiagrumi', 'value' => 86],
            ['label' => 'Regolabarba', 'value' => 87],
            ['label' => 'Piastra Per Capelli', 'value' => 88],
            ['label' => 'Lettore Dvd', 'value' => 89],
            ['label' => 'Cappa Aspirante', 'value' => 90],
            ['label' => 'Lavello', 'value' => 91],
            ['label' => 'Miscelatore', 'value' => 92],
            ['label' => 'Frigo Cantine', 'value' => 93],
            ['label' => 'Trasferimento Tra Punti Vendita', 'value' => 94],
            ['label' => 'Sottovuoto', 'value' => 95],
            ['label' => 'Depilatore', 'value' => 96],
            ['label' => 'Asse Da Stiro', 'value' => 97],
            ['label' => 'Tablet', 'value' => 98],
            ['label' => 'Grattugia', 'value' => 99],
            ['label' => 'Scopa A Vapore', 'value' => 100],
            ['label' => 'Cuffie', 'value' => 101],
            ['label' => 'Aerosol', 'value' => 102],
            ['label' => 'Bancale Pellet', 'value' => 103],
            ['label' => 'R1 Generico', 'value' => 104],
            ['label' => 'R2 Generico', 'value' => 105],
            ['label' => 'R3 Generico', 'value' => 106],
            ['label' => 'R4 Generico', 'value' => 107],
            ['label' => 'R5 Generico', 'value' => 108],
        ];

        return $this->_options;
    }
}
