<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Wishlist\Block\Catalog\Product\ProductList\Item\AddTo\Wishlist $block */
?>
<?php if ($block->getWishlistHelper()->isAllow()) : ?>
    <?php $_product = $block->getProduct(); ?>
    <?php $helper   = $this->helper(\Elightwalk\Core\Helper\Data::class); ?>
    <?php if ($helper->getCustomerWishlist($_product->getId(), true)) : ?>
        <a href="javascript:void(0)" class="action towishlist active" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" role="button">
            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
        </a>
    <?php else : ?>
        <a href="#" class="action towishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" aria-label="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>" data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($block->getProduct()) ?>' data-action="add-to-wishlist" role="button">
            <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
        </a>
    <?php endif; ?>
<?php endif; ?>