<?php
/** @var \Magento\Catalog\Block\Product\View\Gallery $block */

$images = $block->getGalleryImages()->getItems();
$hasImages = count($images) > 0;
?>

<?php if ($hasImages): ?>
    <div class="gallery-photo-video">
        <div class="col-12">
            <h2><?= __('Photo & Video'); ?></h2>

            <div class="tns-inner">
                <div class="tns-slider tns-carousel tns-subpixel tns-calc tns-horizontal" id="product-gallery">
                    <?php foreach ($images as $image): ?>
                        <?php if (!$block->isMainImage($image)): ?>
                            <div class="item tns-item tns-slide-cloned"
                                 data-src="<?= $image->getVideoUrl() ?: $image->getData('medium_image_url'); ?>">
                                <a href="javascript:void(0)" class="product-media-link"
                                   data-media-url="<?= $image->getVideoUrl() ?: $image->getData(
                                       'medium_image_url'
                                   ); ?>">
                                    <img src="<?= $image->getData('medium_image_url'); ?>" alt=""/>
                                </a>
                            </div>
                        <?php endif; ?>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>

    <script>
        require(['jquery', 'Magento_Ui/js/modal/modal', 'tinySlider', 'lightGallery'], function ($, modal, tinySlider, lightGallery) {
            $(document).ready(function () {
                var detailsGalleryDragMove = false;

                var sliderGallery = tns({
                    container: '#product-gallery',
                    items: 2.5,
                    mouseDrag: true,
                    swipeAngle: false,
                    controls: true,
                    nav: false,
                    edgePadding: 50,
                    gutter: 10,
                    lazyload: true,
                    loop: false,
                    "responsive": {
                        "250": {
                            "items": 2,
                        },
                        "780": {
                            "items": 2.5
                        }
                    }
                });

                if(sliderGallery != undefined && sliderGallery != 'undefined') {
                    sliderGallery.events.on('dragEnd', function () {
                        detailsGalleryDragMove = false;
                    });

                    sliderGallery.events.on('dragMove', function () {
                        detailsGalleryDragMove = true;
                    });
                }

                lightGallery(document.getElementById('product-gallery'), {
                    speed: 500,
                });

                var canScroll = true;
                $('#product-gallery').on('wheel', function (event) {
                    var eo = event.originalEvent;
                    var xy = eo.wheelDelta || -eo.detail;
                    var x = eo.wheelDeltaX || (eo.axis === 2 ? xy : 0);
                    var y = eo.wheelDeltaY || (eo.axis === 2 ? xy : 0);

                    if (!canScroll || y !== 0) {
                        return;
                    }

                    canScroll = false;
                    setTimeout(function () {
                        if (x > 50) {
                            $('[data-controls="prev"]').click();
                        } else {
                            $('[data-controls="next"]').click();
                        }

                        canScroll = true;
                    }, 250);
                });
            });
        });
    </script>
<?php endif; ?>
