<?php /** @var \Nextouch\Theme\Block\Pages\Homepage $block */ ?>

<div class="row">
    <div class="col-12">
        <?= $block->createHeroSliderBlock(); ?>
    </div>
</div>

<div class="container">
    <?= $block->createDecisionTreeBlock(); ?>

    <?= $block->createMainBannerBlock(); ?>

    <?= $block->createPromotionsBlock(); ?>

    <?= $block->createNewsBlock(); ?>

    <?= $block->createOffersBlock(); ?>

    <?= $block->createHelpdeskBlock(); ?>
</div>
