<?php
/** @var Magento\Review\Block\Product\View\ListView $block */

use Amasty\AdvancedReview\Helper\BlockHelper;
use Amasty\AdvancedReview\Model\Toolbar\Applier;

$displayedCollection = $block->getReviewsCollection();
$_items = $displayedCollection->getItems();

/** @var BlockHelper $advancedHelper */
$advancedHelper = $block->getData('advanced-review-helper');

$isFilterApplied = $displayedCollection->getFlag(Applier::COLLECTION_FLAG);
?>

<?php if (count($_items) || $isFilterApplied) : ?>
<div class="block review-list" id="customer-reviews">
    <div class="amrev-title-block amreview-customer-review pages">
        <strong class="am-strong">
            <?= __('Reviews'); ?>
        </strong>
    </div>

    <div class="amrev-items-block block-content" data-amload-js="container">
        <?php if (count($_items)): ?>
            <ol class="items amreview-review-items"
                data-mage-init='{
                    "amReview": {
                        "slidesToShow": <?= (int)$advancedHelper->getSlidesToShow(); ?>,
                        "slidesToScroll": 1
                    }
                }'>
                <?php foreach ($_items as $review) : ?>
                    <li class="item review-item amreview-review-wrapper"
                        data-amreview-js="review-entity"
                        data-amreview-id="<?= (int)$review->getId(); ?>"
                        itemscope itemprop="review"
                        itemtype="http://schema.org/Review">
                        <div class="amreview-description-wrap" data-amreview-js="description-wrap">
                            <?php if (count($review->getRatingVotes())) : ?>
                                <?php foreach ($review->getRatingVotes() as $_vote) : ?>
                                    <div class="amstars-rating-container -small"
                                        <?php $stars = $_vote->getValue(); ?>
                                         title="<?= $block->escapeHtml($stars > 1 ? __('%1 stars', $stars) : __('%1 star', $stars)); ?>"
                                         itemprop="reviewRating" itemscope itemtype="http://schema.org/Rating">
                                        <meta itemprop="worstRating" content="1"/>
                                        <meta itemprop="bestRating" content="100"/>
                                        <p class="amstars-stars"
                                           style="width:<?= $block->escapeHtml($_vote->getPercent()); ?>%">
                                                <span itemprop="ratingValue" class="hidden">
                                                    <?= $block->escapeHtml($_vote->getPercent()); ?>%
                                                </span>
                                        </p>
                                    </div>
                                <?php endforeach; ?>
                            <?php endif; ?>

                            <div class="amrev-desc-title">
                                <span class="amreview-title-review" itemprop="name">
                                    <?= $block->escapeHtml($review->getNickname()); ?> -
                                    <?= $block->escapeHtml($review->getTitle()); ?>
                                </span>
                                <div class="amrev-comment-toolbar -nocomments">
                                    <?= $advancedHelper->getHelpfulHtml($review); ?>
                                </div>
                            </div>

                            <div class="amreview-description amshowmore-container"
                                 data-mage-init='{"Amasty_AdvancedReview/js/components/am-show-more": {"maxCharaters": 500}}'
                                 itemprop="description">
                                <span class="amreview-text amshowmore-text" data-amshowmore-js="text">
                                    <?= $block->escapeHtml($review->getDetail()); ?>
                                </span>
                            </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            </ol>
            <div class="toolbar review-toolbar amreview-toolbar-wrap">
                <?= $block->getChildHtml('toolbar'); ?>
            </div>
        <?php else : ?>
            <p class="amreview-review-list -empty">
                <strong><?= $block->escapeHtml(__('No reviews')); ?></strong>
            </p>
        <?php endif; ?>
    </div>
</div>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".amasty-jet-theme .amtheme-reviewform-block": {
            "amPopup": {
                "trigger": "<?= $block->escapeHtml('#amreview-toform'); ?>"
            }
        }
    }
</script>
