<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate

/**  @var $block \Magento\Checkout\Block\Cart\Grid */
?>
<?php $mergedCells = ($this->helper(Magento\Tax\Helper\Data::class)->displayCartBothPrices() ? 2 : 1); ?>
<?= $block->getChildHtml('form_before') ?>
<form action="<?= $block->escapeUrl($block->getUrl('checkout/cart/updatePost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"Magento_Checkout/js/action/update-shopping-cart":
              {"validationURL" : "<?= $block->escapeUrl($block->getUrl('checkout/cart/updateItemQty')) ?>",
              "updateCartActionContainer": "#update_cart_action_container"}
          }'
      class="form form-cart">
    <?= $block->getBlockHtml('formkey') ?>
    <div class="cart table-wrapper<?= $mergedCells == 2 ? ' detailed' : '' ?>">
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-top toolbar"
                 data-attribute="cart-products-toolbar-top"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
        <div id="shopping-cart-table"
             class="cart items data table"
             data-mage-init='{"shoppingCart":{"emptyCartButton": ".action.clear",
               "updateCartActionContainer": "#update_cart_action_container"}}'>

            <?php foreach ($block->getItems() as $_item): ?>
                <?= $block->getItemHtml($_item) ?>
            <?php endforeach ?>
        </div>
        <?php if ($block->getPagerHtml()): ?>
            <div class="cart-products-toolbar cart-products-toolbar-bottom toolbar"
                 data-attribute="cart-products-toolbar-bottom"><?= $block->getPagerHtml() ?>
            </div>
        <?php endif ?>
    </div>
    <div class="cart main actions">
        <?php if ($block->getContinueShoppingUrl()): ?>
            <a class="action continue"
               href="<?= $block->escapeUrl($block->getContinueShoppingUrl()) ?>"
               title="<?= $block->escapeHtml(__('Continue Shopping')) ?>">
                <span><?= $block->escapeHtml(__('Continue Shopping')) ?></span>
            </a>
        <?php endif; ?>
        <?php if ($block->getViewModel()->isClearShoppingCartEnabled()): ?>
            <button type="button"
                    name="update_cart_action"
                    data-cart-empty=""
                    value="empty_cart"
                    title="<?= $block->escapeHtml(__('Clear Shopping Cart')) ?>"
                    class="action clear" id="empty_cart_button">
                <span><?= $block->escapeHtml(__('Clear Shopping Cart')) ?></span>
            </button>
        <?php endif ?>
        <button type="submit"
                name="update_cart_action"
                data-cart-item-update=""
                value="update_qty"
                title="<?= $block->escapeHtml(__('Update Shopping Cart')) ?>"
                class="action update">
            <span><?= $block->escapeHtml(__('Update Shopping Cart')) ?></span>
        </button>
        <input type="hidden" value="" id="update_cart_action_container" data-cart-item-update=""/>
    </div>
</form>
<?= $block->getChildHtml('checkout.cart.order.actions') ?>
<?= $block->getChildHtml('shopping.cart.table.after') ?>

<script>
    require(['jquery'], function ($) {
        $(".more-less").on('click', function () {
            if(!$(this).hasClass('disabled')) {
                var qtyField = $(this).parent().find('input');
                var qtyValue = parseInt($(qtyField).val());
                if ($(this).hasClass('less-button') && qtyValue > 0) {
                    qtyValue = qtyValue - 1
                } else {
                    qtyValue = qtyValue + 1
                }
                $(qtyField).val(qtyValue);
                if (qtyValue <= 0) {
                    $(this).parent().find('.less-button').addClass('disabled')
                } else {
                    $(this).parent().find('.less-button').removeClass('disabled')
                }
            }
        });
    });
</script>

<script>
    require(['jquery',
        'Magento_Customer/js/model/authentication-popup',
        'Magento_Customer/js/customer-data',
    ], function ($,authenticationPopup,customerData) {
        var cart = customerData.get('cart'),
            customer = customerData.get('customer'),
            checkoutButton = $('.checkout.methods'),
            loginContinueButton = $('.block-customer-login .continue-url a');

        $(checkoutButton).on('click', function(event) {
            event.stopPropagation();
            event.preventDefault();
            if (!customer().firstname) {
                authenticationPopup.showModal();
            }
            else {

            }
        });

        $('body').on('click', function(event) {
            var target = $(event.target);
            if(!target.closest('.modal-popup-crosssell').length &&
                $('.modal-popup-crosssell').hasClass("_show")) {
                authenticationPopup.hideModal();
                $('.block-modal-crosssell-modal-container').modal('closeModal');
            }
        });

        $(document).ready(function () {
            $('body').on('click', '.block-customer-login .continue-url a', function (event) {
                var crossSellContainer = $('.block-modal-crosssell-modal-container');
                if(crossSellContainer.length) {
                    event.stopPropagation();
                    event.preventDefault();
                    authenticationPopup.hideModal();
                    var checkoutUrl = $(this).attr('href');
                    $(crossSellContainer).modal('openModal');
                }
                else {
                    var checkoutUrl = $(this).attr('href');
                    window.location.href = checkoutUrl;
                }

            });
        });





    });
</script>
