<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis 

/**
 * @var $block \Magento\Catalog\Block\Product\View\Description
 */
?>

<?php $_product = $block->getProduct(); ?>
<?php if (!$_product instanceof \Magento\Catalog\Model\Product) : ?>
    <?php return; ?>
<?php endif; ?>

<?php /* $_helper                = $this->helper(Magento\Catalog\Helper\Output::class); ?>
<?php $_call                  = $block->getAtCall(); ?>
<?php $_code                  = $block->getAtCode(); ?>
<?php $_className             = $block->getCssClass(); ?>
<?php $_attributeLabel        = $block->getAtLabel(); ?>
<?php $_attributeType         = $block->getAtType(); ?>
<?php $_attributeAddAttribute = $block->getAddAttribute(); ?>
<?php $renderLabel            = true; */ ?>

<?php /* if ($_attributeLabel == 'none') : ?>
    <?php $renderLabel = false; ?>
<?php endif; */ ?>

<?php /* if ($_attributeLabel && $_attributeLabel == 'default') : ?>
    <?php $_attributeLabel = $_product->getResource()->getAttribute($_code)->getStoreLabel(); ?>
<?php endif; ?>
<?php if ($_attributeType && $_attributeType == 'text') : ?>
    <?php $_attributeValue = ($_helper->productAttribute($_product, $_product->$_call(), $_code)) ? $_product->getAttributeText($_code) : ''; ?>
<?php else : ?>
    <?php $_attributeValue = $_helper->productAttribute($_product, $_product->$_call(), $_code); ?>
<?php endif; */ ?>

<?php /* if ($_attributeValue) : ?>
    <h5 class="heading-overview"><?= __('Product View'); ?></h5>
    <div class="product attribute <?= $block->escapeHtmlAttr($_className); ?>">
        <?php if ($renderLabel) : ?>
            <strong class="type"><?= $block->escapeHtml($_attributeLabel); ?></strong>
        <?php endif; ?>
        <div class="value" <?= $_attributeAddAttribute; ?>><?= $_attributeValue; ?></div>
    </div>
<?php endif; */ ?>

<?php $attributeList = $this->getLayout()->createBlock("Magento\Catalog\Block\Product\View\Description")->setTemplate("Magento_Catalog::product/attribute-list.phtml")->setProduct($_product)->setPageAction('product_view'); ?>
<?= $attributeList->toHtml(); ?>

<?php $attributeSetId = $_product->getAttributeSetId(); ?>