<?php
/** @var \Nextouch\Theme\Block\Catalog\Product\View\EcoChoice $block */

use Nextouch\Catalog\Api\Data\ProductInterface;

$rating = $block->getProduct()->getEcoChoiceLevel();
?>

<div class="product-ecochoice">
    <div id="product-eco-choice-collapsible">
        <div data-role="title">
            <span class="icon-veg"><img src="<?= $block->getViewFileUrl('images/veg_icon.svg'); ?>" width="60" alt=""/></span>
            <h2 class="text-sm-start">
                <?= __('Ecological / eco-friendly choice'); ?>
                <span class="eco-rating eco-rating-<?= $rating; ?>">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </span>
            </h2>
        </div>

        <div data-role="content" class="more-less-content">
            <div class="more-less-wrapper">
            <?= $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
                $block->getProduct(),
                $block->getProduct()->getEcoChoice(),
                ProductInterface::ECO_CHOICE
            ); ?>
            </div>
            <div class="more-less">
                <span class="more"> <?= __('Show more') ?></span>
                <span class="less"> <?= __('Show less') ?></span>
            </div>
        </div>
    </div>
</div>
