<?php /** @var \Magento\Catalog\Block\Product\View\Description $block */ ?>
<?php

$rating = 3; // TODO: add dynamic value; 0-5 int value

?>

<div id="product-eco-choice-collapsible">
    <div data-role="title">
        <h2 class="text-center text-sm-start">
            <?= __('Ecological / eco-friendly choice'); ?>
            <span class="eco-rating eco-rating-<?= $rating; ?>">
                <span></span>
                <span></span>
                <span></span>
                <span></span>
                <span></span>
            </span>
        </h2>
    </div>

    <div data-role="content">
        <?= $this->helper(Magento\Catalog\Helper\Output::class)->productAttribute(
            $block->getProduct(),
            $block->getProduct()->getEcoChoice(),
            'eco_choice'
        ); ?>
    </div>
</div>

<script>
    require(['jquery', 'collapsible'], function ($) {
        $("#product-eco-choice-collapsible").collapsible({
            collapsible: true,
            openedState: 'active',
            animate: {duration: 1000, easing: 'easeInCubic'}
        });
    });
</script>
