<?php
/** @var \Magento\Catalog\Block\Product\View\Gallery $block */

$images = $block->getGalleryImages()->getItems();
?>

<div class="gallery-photo-video">
    <div class="col-12">
        <h2><?= __('Photo & Video'); ?></h2>

        <div class="tns-inner">
            <div class="tns-slider tns-carousel tns-subpixel tns-calc tns-horizontal" id="product-gallery">
                <?php foreach ($images as $image): ?>
                    <?php if (!$block->isMainImage($image)): ?>
                        <div class="item tns-item tns-slide-cloned">
                            <a href="javascript:void(0)" class="product-media-link" data-media-url="<?= $image->getVideoUrl() ?: $image->getData('medium_image_url'); ?>">
                                <img src="<?= $image->getData('medium_image_url'); ?>" alt=""/>
                            </a>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<div id="product-media-modal">
    <div class="modal-body-content text-center">
        <iframe src="" width="100%" allow="autoplay; encrypted-media" allowfullscreen style="height: calc(80vh - 50px)"></iframe>
    </div>
</div>

<script>
    require(['jquery', 'Magento_Ui/js/modal/modal', 'tinySlider'], function ($, modal) {
        $(document).ready(function () {
            var $productMediaModal = $('#product-media-modal');
            var $iframe = $productMediaModal.find('iframe');


            modal({
                type: 'popup',
                modalClass: 'product-media-popup',
                responsive: true,
                buttons: [],
            }, $productMediaModal);


            $('.tns-inner .product-media-link').on('click', function () {
                if(!detailsGalleryDragMove) {
                    var mediaUrl = $(this).data('media-url');
                    $iframe.prop('src', mediaUrl);
                    $productMediaModal.modal('openModal');
                }
            });

            $iframe.on('load', function() {
                $iframe.contents().find('body').css('text-align', 'center');
            });
        });

        var sliderGallery = tns({
            container: '#product-gallery',
            items: 2,
            mouseDrag: true,
            swipeAngle: false,
            controls: false,
            nav: false,
            edgePadding: 40,
            gutter: 10,
            lazyload: true,
            loop: false,
            "responsive": {
                "250": {
                    "items": 2,
                },
                "780": {
                    "items": 2
                }
            }
        });


        var detailsGalleryDragMove = false;
        sliderGallery.events.on('dragEnd', function (info) {
            detailsGalleryDragMove = false;
        });
        sliderGallery.events.on('dragMove', function (info) {
            detailsGalleryDragMove = true;
        });
    });
</script>
