<?php
/** @var \Magento\Catalog\Block\Product\View\Gallery $block */

$images = $block->getGalleryImages()->getItems();
?>

<div class="row">
    <div class="col-12">
        <h2><?= __('Photo & Video'); ?></h2>

        <div class="tns-inner">
            <div class="tns-slider tns-carousel tns-subpixel tns-calc tns-horizontal" id="product-gallery">
                <?php foreach ($images as $image): ?>
                    <?php if (!$block->isMainImage($image)): ?>
                        <div class="item tns-item tns-slide-cloned">
                            <img src="<?= $image->getData('medium_image_url'); ?>" alt=""/>
                        </div>
                    <?php endif; ?>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</div>

<script>
    require(['tinySlider'], function () {
        tns({
            container: '#product-gallery',
            items: 3,
            mouseDrag: true,
            swipeAngle: false,
            controls: false,
            nav: false,
        });
    });
</script>
