<?php /** @var \Magento\Catalog\Block\Product\ProductList\Toolbar $block */ ?>

<div class="row">
    <div class="col-12 mb-4">
        <div class="d-flex align-items-center justify-content-center justify-content-sm-start">
            <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/list/ico-cuffie.svg'); ?>" width="35" alt=""/>
            <div class="text-start ms-5">
                <strong class="d-block"><?= __('Do you need help choosing?'); ?></strong>
                <span class="d-block"><?= __('ask the nextouch team.'); ?></span>
            </div>
        </div>
    </div>

    <div class="col-12">
        <div class="d-flex align-items-center justify-content-center justify-content-sm-start">
            <img src="<?= $block->getViewFileUrl('Magento_Catalog::images/list/ico-pin.svg'); ?>" width="35" alt=""/>
            <div class="text-start ms-5">
                <strong class="d-block"><?= __('Come to the shop!'); ?></strong>
                <span class="d-block"><?= __('find the store closest to you.'); ?></span>
            </div>
        </div>
    </div>
</div>
