<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?= $block->escapeHtml(__('Sort By')) ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php $sorterSelected = __('Name'); ?>
        <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
            <option value="<?= $block->escapeHtmlAttr($_key) ?>"
                <?php if ($block->isOrderCurrent($_key)) :?>
                    <?php $sorterSelected = $block->escapeHtml(__($_order)) ?>
                    selected="selected"
                <?php endif; ?>
            >
                <?= $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <div class="dropdown-cloned">
        <div class="selected-cloned"><?=$sorterSelected ?></div>
        <div class="options-cloned sorter-dropdown-options">
            <?php foreach ($block->getAvailableOrders() as $_key => $_order) :?>
                <div class="option-cloned <?php if ($block->isOrderCurrent($_key)) :?>current<?php endif; ?>">
                    <?= $block->escapeHtml(__($_order)) ?>
                </div>
            <?php endforeach; ?>
        </div>
    </div>

    <?php if ($block->getCurrentDirection() == 'desc') :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Ascending Direction')) ?>"
           href="#"
           class="action sorter-action sort-desc"
           data-role="direction-switcher"
           data-value="asc">
            <svg version="1.1" fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 512 512">
                <path d="M160 384v-384h-64v384h-80l112 112 112-112h-80z"></path>
                <path d="M464 512h-128c-5.9 0-11.322-3.248-14.107-8.45-2.783-5.202-2.479-11.515 0.795-16.425l111.416-167.125h-98.104c-8.836 0-16-7.164-16-16s7.164-16 16-16h128c5.9 0 11.322 3.248 14.107 8.45 2.783 5.202 2.479 11.515-0.795 16.425l-111.415 167.125h98.103c8.836 0 16 7.164 16 16s-7.164 16-16 16z"></path>
                <path d="M510.311 200.843l-96.001-192c-2.71-5.421-8.251-8.845-14.311-8.845s-11.601 3.424-14.312 8.845l-95.998 192c-3.952 7.903-0.748 17.515 7.155 21.466 2.297 1.148 4.738 1.693 7.144 1.693 5.868 0 11.52-3.242 14.322-8.849l27.578-55.155h108.223l27.578 55.155c3.951 7.903 13.562 11.105 21.466 7.155 7.904-3.951 11.108-13.562 7.156-21.465zM361.889 127.998l38.11-76.223 38.112 76.223h-76.222z"></path>
            </svg>

            <span><?= $block->escapeHtml(__('Set Ascending Direction')) ?></span>
        </a>
    <?php else :?>
        <a title="<?= $block->escapeHtmlAttr(__('Set Descending Direction')) ?>"
           href="#"
           class="action sorter-action sort-asc"
           data-role="direction-switcher"
           data-value="desc">
            <svg version="1.1" fill="currentColor" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 512 512">
                <path d="M160 384v-384h-64v384h-80l112 112 112-112h-80z"></path>
                <path d="M464 224h-128c-5.9 0-11.322-3.248-14.107-8.45-2.783-5.203-2.479-11.515 0.795-16.425l111.416-167.125h-98.104c-8.836 0-16-7.164-16-16s7.164-16 16-16h128c5.9 0 11.322 3.248 14.107 8.45 2.783 5.203 2.479 11.515-0.795 16.425l-111.415 167.125h98.103c8.836 0 16 7.164 16 16s-7.164 16-16 16z"></path>
                <path d="M510.311 488.845l-96.001-192c-2.71-5.421-8.251-8.845-14.311-8.845s-11.601 3.424-14.312 8.845l-95.998 192c-3.952 7.903-0.748 17.515 7.155 21.466 2.297 1.148 4.738 1.693 7.144 1.693 5.868 0 11.52-3.242 14.322-8.849l27.579-55.155h108.223l27.578 55.155c3.951 7.903 13.562 11.105 21.466 7.155s11.107-13.562 7.155-21.465zM361.889 416l38.11-76.223 38.113 76.223h-76.223z"></path>
            </svg>

            <span><?= $block->escapeHtml(__('Set Descending Direction')) ?></span>
        </a>
    <?php endif; ?>
</div>


<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function () {


            $('.selected-cloned').on('click', function(event) {
                $(this).parent().toggleClass('active');
                event.stopPropagation();
            });

            $('.options-cloned').on('click', '.option-cloned', function(event) {
                event.stopPropagation();
                var index = $(this).index();
                var selectedOption = $('#sorter option').eq(index);
                $('.selected-cloned').text($(selectedOption).text());
                $(selectedOption).prop('selected',true);
                $(selectedOption).parent().trigger('click').trigger('change');
            });

            $(window).on('click', function() {
                $('.dropdown-cloned').removeClass('active');
            });

        });
    });
</script>
