<script>
    require(['jquery', 'swiper', 'domReady!'], function ($) {
        new Swiper('.category-slider', {                        
            nextButton: '.category-slider .swiper-button-next',
            prevButton: '.category-slider .swiper-button-prev',
            pagination: '.category-slider-pagination',
            paginationClickable: true,
            slidesPerView: 4,
            spaceBetween: 60,
            breakpoints: {            
                640: {
                    slidesPerView: 1.2,
                    spaceBetween: 20,
                },
                768: {
                    slidesPerView: 2,
                    spaceBetween: 30,
                },
                1024: {
                    slidesPerView: 3,
                    spaceBetween: 60,
                },
                1200: {
                    slidesPerView: 3,
                    spaceBetween: 60,
                },
                1500: {
                    slidesPerView: 4,
                    spaceBetween: 60,
                },
            },
        });

    });
</script>