<script>
    (function() {
        require([
            "jquery",
            "jquery/ui",
        ], function($, ui) {
            $(document).ready(function() {
                
              
                // Mobile menu search
                // $(document).on("click", ".footer-links-title", function() {
                //     $(".mb-mobile-search-wrapper").addClass("mb-mobile-search-wrapper-active");
                // });

                $(document).on("click", ".footer-links-title", function() {
                    console.log("died")
                    $(this).parent().toggleClass("dropdown-active");
                });
               
            });
        });
    })();
</script>
