<?php
/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$sideaConfig = $this->helper(Nextouch\Sidea\Helper\SideaConfig::class);
$viewModel = $block->getViewModel();
$contactFrequentQuestions = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_frequent_questions');
$contactusContent = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contactus_content');
$aboutServicesSlider = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_services_slider');
$aboutBanners = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_banners');
?>
<form class="form contact"
      action="<?= $block->escapeUrl($sideaConfig->getContactActionUrl()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <!-- <?= $contactFrequentQuestions->toHtml() ?> -->

    <div class="contactus-content-main">
        <h2 class="text-h2"><?= $block->escapeHtml(__('Contact Us')) ?></h2>
        <div class="contactus-content"><?= $contactusContent->toHtml() ?></div>
    </div>

    <div class="contactus-form">
        <fieldset class="fieldset">
            <input type=hidden name="orgid" value="<?= $block->escapeHtml($block->getContactOriginId()) ?>">
            <input type=hidden name="retURL" value="<?= $block->escapeUrl($block->getUrl('contact')) ?>">
            <div class="field name required">
                <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
                <div class="control">
                    <input name="name"
                        id="name"
                        title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                        value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                        class="input-text"
                        placeholder="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                        type="text"
                        data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field email required">
                <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input name="email"
                        id="email"
                        title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                        value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                        class="input-text"
                        type="email"
                        placeholder="<?= $block->escapeHtml(__('Email')) ?>"
                        data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>
            <div class="field phone required">
                <label class="label" for="phone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
                <div class="control">
                    <input name="phone"
                        id="phone"
                        title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                        value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                        class="input-text"
                        type="tel"
                        placeholder="<?= $block->escapeHtml(__('Phone Number')) ?>"
                        data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field subject required">
                <label class="label" for="subject"><span><?= $block->escapeHtml(__('Subject')) ?></span></label>
                <div class="control">
                    <input name="subject"
                        id="subject"
                        title="<?= $block->escapeHtmlAttr(__('Subject')) ?>"
                        class="input-text"
                        type="text"
                        placeholder="<?= $block->escapeHtml(__('Subject')) ?>"
                        data-validate="{required:true}"/>
                </div>
            </div>
            <div class="field description required">
                <label class="label" for="description">
                    <span><?= $block->escapeHtml(__('What are you contacting us for?')) ?></span>
                </label>
                <div class="control">
                    <textarea name="description"
                            id="description"
                            title="<?= $block->escapeHtmlAttr(__('What are you contacting us for?')) ?>"
                            class="input-text"
                            cols="5"
                            placeholder="<?= $block->escapeHtml(__('What are you contacting us for?')) ?>"
                            rows="8"
                            data-validate="{required:true}"
                            style="resize: none;"
                    ><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
                </div>
            </div>
            <div class="field choice required">
                <input id="00N3N00000KBGOq"
                    name="00N3N00000KBGOq"
                    type="checkbox"
                    value="1"
                    data-validate="{required:true}"
                    checked>
                <label class="label" for="00N3N00000KBGOq">
                    <?= $block->escapeHtml(
                        __("Dichiaro di accettare i Termini e Condizioni e di aver preso visione dell'Informativa Privacy resa ai sensi dell'art. 13 Reg. UE 679/2016 (GDPR).")
                    ) ?>
                </label>
            </div>
            <div class="field choice">
                <input id="00N3N00000KBGLS"
                    name="00N3N00000KBGLS"
                    type="checkbox"
                    value="1">
                <label class="label" for="00N3N00000KBGLS">
                    <?= $block->escapeHtml(
                        __("Acconsento al trattamento dei miei dati personali per l'invio di comunicazioni commerciali e pubblicitare da parte di NexTouch S.p.A. via e-mail e SMS.")
                    ) ?>
                </label>
            </div>
            <div class="field choice">
                <input id="00N3N00000KBZat"
                    name="00N3N00000KBZat"
                    type="checkbox"
                    value="1">
                <label class="label" for="00N3N00000KBZat">
                    <?= $block->escapeHtml(
                        __("Acconsento al trattamento dei miei dati personali per scopi di profilazione mediante la creazione di un profilo utente al fine di inviare comunicazioni personalizzate in linea con i miei interessi esclusivamente da parte di NexTouch S.p.A. anche attraverso l'uso di strumento elettronici e automatizzati.")
                    ) ?>
                </label>
            </div>
            <?= $block->getChildHtml('form.additional.info') ?>
        </fieldset>
        <div class="actions-toolbar">
            <p>
                <?= $block->escapeHtml('The assistance service is active from Monday to Friday from 00:00 to 00:00.') ?><br>
                <?= $block->escapeHtml('Our operators will reply as soon as possible.') ?>
            </p>

            <div class="primary">
                <input type="hidden" name="hideit" id="hideit" value="" />
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </div>
</form>

<div style="margin-top: 100px">
    <?= $aboutServicesSlider->toHtml() ?>
</div>

<div style="margin-top: 100px">
    <?= $aboutBanners->toHtml() ?>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
