<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php
/**
 * Create account form template
 *
 * @var $block \Magento\Customer\Block\Form\Register
 */
?>
<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<?php
/** @var \Magento\Customer\Helper\Address $addressHelper */
$addressHelper = $block->getData('addressHelper');
/** @var \Magento\Directory\Helper\Data $directoryHelper */
$directoryHelper = $block->getData('directoryHelper');
$formData = $block->getFormData();
?>
<div class="columns-customer-login login-container">

    <div class="col1 customer-login-left-block">
        <h2><?= $block->escapeHtml(__('Create account')) ?></h2>
        <div class="form-create-desc"><span class="createinfo-trigger" data-trigger="createinfo"><?= $block->escapeHtml(__('Scopri i vantaggi')) ?></span>
            <?= $block->escapeHtml(__(' della registrazione nel mondo Andronico. Sei già cliente? ')) ?><a href="<?= $block->escapeUrl($block->getUrl('customer/account/login')) ?>" class="action login"><span><?= $block->escapeHtml(__('Accedi')) ?></span></a>
                            </div>
        <div class="form-create-info-popup" data-bind="mageInit: {
                'Magento_Ui/js/modal/modal':{
                    'type': 'popup',
                    'modalClass':'modalcreateinfo',
                    'parentModalClass':'modalcreateinfowrapper',
                    'title': '<?= $block->escapeHtml(__('I vantaggi dei nostri utenti')) ?>',
                    'trigger': '[data-trigger=createinfo]',
                    'responsive': true,
                    'zIndex': '898',
                    'buttons': false
                }}">
                <div class="content">
                    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('benefits-our-users')->toHtml(); ?>
                </div>
            </div>
            
    <form class="form create account form-create-account"
          action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
          method="post"
          id="form-validate"
          enctype="multipart/form-data"
          autocomplete="off">
        <?= /* @noEscape */ $block->getChildHtml('form_fields_before_in_form') ?>
        <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
        <fieldset class="fieldset create info">
            <legend class="legend"><span><?= $block->escapeHtml(__('Personal Information')) ?></span></legend>
            <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>"/>
            <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>"/>
            <?= $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Name::class)
                ->setObject($formData)
                ->setForceUseCustomerAttributes(true)
                ->toHtml()
            ?>

            <div class="field required">
                <label for="email_address" class="label"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                <div class="control">
                    <input type="email"
                           name="email"
                           id="email_address"
                           autocomplete="email"
                           value="<?= $block->escapeHtml($formData->getEmail()) ?>"
                           title="<?= $block->escapeHtml(__('Email')) ?>"
                           plachholder="<?= $block->escapeHtml(__('Email')) ?>"
                           class="input-text"
                           data-validate="{required:true, 'validate-email':true}"/>
                </div>
            </div>

            <?php $_dob = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Dob::class) ?>
            <?php if ($_dob->isEnabled()): ?>
                <?= $_dob->setDate($formData->getDob())->toHtml() ?>
            <?php endif ?>

            <?php $_taxvat = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Taxvat::class) ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <?= $_taxvat->setTaxvat($formData->getTaxvat())->toHtml() ?>
            <?php endif ?>

            <?php $_gender = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Gender::class) ?>
            <?php if ($_gender->isEnabled()): ?>
                <?= $_gender->setGender($formData->getGender())->toHtml() ?>
            <?php endif ?>

            <?php $customerAttributes = $block->getChildBlock('customer_form_user_attributes');?>
            <?php if ($customerAttributes): ?>
                <?php $customerAttributes->setObject($formData)
                    ->setEntityType('customer')
                    ->setShowContainer(false);?>
                <?php $block->restoreSessionData($customerAttributes->getMetadataForm());?>
                <?= $customerAttributes->toHtml() ?>
            <?php endif;?>

            <?= $block->getChildHtml('fieldset_create_info_additional') ?>
        

    <?php if ($block->getShowAddressFields()): ?>
        <!-- <fieldset class="fieldset address"> -->
            <legend class="legend"><span><?= $block->escapeHtml(__('Address Information')) ?></span></legend>
            <input type="hidden" name="create_address" value="1"/>
            <div class="field country required">
                <label for="country" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span>
                </label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span>
                </label>
                <div class="control">
                    <select id="region_id"
                            name="region_id"
                            title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                            class="validate-select region_id">
                        <option value="">
                            <?= $block->escapeHtml(__('Please select a region, state or province.')) ?>
                        </option>
                    </select>
                    <input type="text"
                           id="region"
                           name="region"
                           value="<?= $block->escapeHtml($block->getRegion()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>"
                           class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('region') ?>"/>
                </div>
            </div>
            <?= /* @noEscape */
            $secureRenderer->renderTag(
                'style',
                [],
                '#region_id { display:none; }
                    #region { display:none; }
                ',
                true
            );
            ?>

            <div class="field required">
                <label for="city" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="city"
                           value="<?= $block->escapeHtmlAttr($formData->getCity()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>"
                           class="input-text <?= /* @noEscape */ $addressHelper->getAttributeValidationClass('city') ?>"
                           id="city"/>
                </div>
            </div>

            <?php $_streetValidationClass = $addressHelper->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span>
                </label>
                <div class="control">
                    <input type="text"
                           name="street[]"
                           value="<?= $block->escapeHtml($formData->getStreetLine(1)) ?>"
                           title="<?= $block->escapeHtml(__('Street Address')) ?>"
                           id="street_1"
                           plachholder="<?= $block->escapeHtml(__('Street Address')) ?>"
                           class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"/>
                    <div class="nested">
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $addressHelper->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <div class="field additional">
                            <label class="label" for="street_<?= /* @noEscape */ $_i ?>">
                                <span><?= $block->escapeHtml(__('Street Address %1', $_i)) ?></span>
                            </label>
                            <div class="control">
                                <input type="text"
                                       name="street[]"
                                       value="<?= $block->escapeHtml($formData->getStreetLine($_i - 1)) ?>"
                                       title="<?= $block->escapeHtml(__('Street Address %1', $_i)) ?>"
                                       plachholder="<?= $block->escapeHtml(__('Street Address %1', $_i)) ?>"
                                       id="street_<?= /* @noEscape */ $_i ?>"
                                       class="input-text <?= /* @noEscape */ $_streetValidationClass ?>"/>
                            </div>
                        </div>
                    <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span>
                </label>
                <div class="control">
                    <?php $zipValidationClass = $addressHelper->getAttributeValidationClass('postcode'); ?>
                    <input type="text"
                           name="postcode"
                           value="<?= $block->escapeHtml($formData->getPostcode()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                           id="zip"
                           plachholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>"
                           class="input-text validate-zip-international <?= /* @noEscape */ $zipValidationClass ?>"
                           data-validate="{'required':true, 'validate-zip-international':true}"/>
                </div>
            </div>

            <div class="field telephone required">
                <label for="telephone" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('telephone') ?></span>
                </label>
                <div class="control">
                    <?php $phoneValidationClass = $addressHelper->getAttributeValidationClass('telephone'); ?>
                    <input type="text"
                           name="telephone"
                           id="telephone"
                           value="<?= $block->escapeHtml($formData->getTelephone()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('telephone') ?>"
                           plachholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('telephone') ?>"
                           class="input-text <?= /* @noEscape */ $phoneValidationClass ?>"/>
                </div>
            </div>

            <div class="field fiscal_code required">
                <label for="fiscal_code" class="label">
                    <span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('fiscal_code') ?></span>
                </label>
                <div class="control">
                    <?php $fiscalCodeValidationClass = $addressHelper->getAttributeValidationClass('fiscal_code'); ?>
                    <input type="text"
                           name="address[fiscal_code]"
                           value="<?= $block->escapeHtml($formData->getFiscalCode()) ?>"
                           title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('fiscal_code') ?>"
                           plachholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('fiscal_code') ?>"
                           id="fiscal_code"
                           class="input-text <?= /* @noEscape */ $fiscalCodeValidationClass ?>"
                           data-validate="{'required':true, 'pattern':'^([A-Z]{6}[0-9LMNPQRSTUV]{2}[ABCDEHLMPRST]{1}[0-9LMNPQRSTUV]{2}[A-Z]{1}[0-9LMNPQRSTUV]{3}[A-Z]{1})$|([0-9]{11})$'}"/>
                </div>
            </div>

            <input type="hidden" name="default_billing" value="1"/>
            <input type="hidden" name="default_shipping" value="1"/>
        <!-- </fieldset> -->

    <?php endif; ?>
        
            <legend class="legend"><span><?= $block->escapeHtml(__('Sign-in Information')) ?></span></legend>
            <div class="field password required">
                <label for="password" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                <div class="control">
                    <?php $requiredCharacterClassesNumber = $block->escapeHtmlAttr(
                        $block->getRequiredCharacterClassesNumber()
                    ); ?>
                    <input type="password" name="password" id="password"
                           title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           plachholder="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           class="input-text"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= /* @noEscape */ $requiredCharacterClassesNumber ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off">
                    <div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label">
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirmation required">
                <label for="password-confirmation" class="label">
                    <span><?= $block->escapeHtml(__('Confirm Password')) ?></span>
                </label>
                <div class="control">
                    <input type="password"
                           name="password_confirmation"
                           title="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>"
                           plachholder="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>"
                           id="password-confirmation"
                           class="input-text"
                           data-validate="{required:true, equalTo:'#password'}"/>
                </div>
            </div>
            </fieldset>
            <div class="field choice" data-bind="scope: 'showPassword'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            
            <div class="register-info-col">
                <div class="field is_privacy_policy_checked required">
                    <div class="control">
                        <input type="checkbox"
                            id="is_privacy_policy_checked"
                            name="is_privacy_policy_accepted"
                            class="input-checkbox checkbox"
                            value="1"
                            data-validate="{required:true, 'validate-one-required-by-name':true}">
                        <label for="is_privacy_policy_checked" class="label">
                            <?= __("Dichiaro di accettare i Termini e Condizioni e di aver preso visione dell'Informativa Privacy resa ai sensi dell'art. 13 Reg. UE 679/2016 (GDPR).") ?>
                        </label>
                    </div>
                </div>

                <div class="field newsletter">
                    <div class="control">
                        <input type="checkbox"
                            id="is_subscribed"
                            name="is_subscribed"
                            class="input-checkbox checkbox"
                            value="1">
                        <label for="is_subscribed" class="label">
                            <?= __("Acconsento al trattamento dei miei dati personali per l'invio di comunicazioni commerciali e pubblicitare da parte di NexTouch S.p.A. via e-mail e SMS.") ?>
                        </label>
                    </div>
                </div>

                <div class="field is_web_profiling_checked">
                    <div class="control">
                        <input type="checkbox"
                            id="is_web_profiling_checked"
                            name="is_web_profiling_accepted"
                            class="input-checkbox checkbox"
                            value="1">
                        <label for="is_web_profiling_checked" class="label">
                            <?= __("Acconsento al trattamento dei miei dati personali per scopi di profilazione mediante la creazione di un profilo utente al fine di inviare comunicazioni personalizzate in linea con i miei interessi esclusivamente da parte di NexTouch S.p.A. anche attraverso l'uso di strumento elettronici e automatizzati.") ?>
                        </label>
                    </div>
                </div>
            </div>
        <!-- </fieldset> -->

        <!-- <fieldset class="fieldset additional_info"> -->
            <?= $block->getChildHtml('form_additional_info') ?>
        <!-- </fieldset> -->

            <div class="primary">
                <button type="submit"
                        class="action submit primary"
                        title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>">
                    <span><?= $block->escapeHtml(__('Create an Account')) ?></span>
                </button>
            </div>
            <div class="secondary">
                <a class="action back"
                   href="<?= $block->escapeUrl($block->getBackUrl()) ?>">
                    <span><?= $block->escapeHtml(__('Back')) ?></span>
                </a>
            </div>
            
    </form>
    <?php if ($block->getShowAddressFields()): ?>
        <?php
        $displayAllRegions = $block->getConfig("general/region/display_all") ? "true" : "false";
        ?>
    <script type="text/x-magento-init">
        {
            "#country": {
                "regionUpdater": {
                    "optionalRegionAllowed": <?= /* @noEscape */ $displayAllRegions ?>,
                    "regionListId": "#region_id",
                    "regionInputId": "#region",
                    "postcodeId": "#zip",
                    "form": "#form-validate",
                    "regionJson": <?= /* @noEscape */ $directoryHelper->getRegionJson() ?>,
                    "defaultRegion": "<?= /* @noEscape */ $formData->getRegionId() ?>",
                    "countriesWithOptionalZip": <?= /* @noEscape */ $directoryHelper->getCountriesWithOptionalZip(true) ?>
                }
            }
        }
    </script>
    <?php endif; ?>
    <script type="text/x-magento-init">
        {
            "*": {
                "Magento_CustomerCustomAttributes/validation": {
                    "ignore": <?= (int) ($_dob->isEnabled() || $customerAttributes->hasUserDefinedAttributes()) ?>,
                    "hasUserDefinedAttributes": <?= (int) $customerAttributes->hasUserDefinedAttributes() ?>,
                    "isDobEnabled": <?= (int) $_dob->isEnabled() ?>,
                    "disableAutoComplete": true,
                    "mixins": [
                        "Magento_CustomerCustomAttributes/error-placement",
                        "Magento_CustomerCustomAttributes/validation-ignore"
                    ]
                },
                "Magento_Customer/js/block-submit-on-send": {
                    "formId": "form-validate"
                },
                "Magento_Ui/js/core/app": {
                    "components": {
                        "showPassword": {
                            "component": "Magento_Customer/js/show-password",
                            "passwordSelector": "#password,#password-confirmation"
                        }
                    }
                }
            },
            ".field.password": {
                "passwordStrengthIndicator": {
                    "formSelector": "form.form-create-account"
                }
            }
        }
    </script>
    </div>

        <div class="col2 customer-login-right-block">
            <?= $block->getChildHtml('customer.login.right.block') ?>
        </div>
    </div>
