<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Information')) ?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <div class="box-content">
                <div class="block block box-content-col">
                    <div class="block-title">
                        <?= $block->escapeHtml(__('Name')) ?>
                    </div>
                    <div class="block-title">
                        <?= $block->escapeHtml($block->getCustomer()->getFirstname()) ?>
                    </div>
                    <div class="block-edit">
                        <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>"><?= $block->escapeHtml(__('Edit')) ?></a>
                    </div>
                </div>
                <div class="block box-content-col">
                    <div class="block-title">
                        <?= $block->escapeHtml(__('Last Name')) ?>
                    </div>
                    <div class="block-title">
                        <?= $block->escapeHtml($block->getCustomer()->getLastName()) ?><br>
                    </div>
                    <div class="block-edit">
                        <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>"><?= $block->escapeHtml(__('Edit')) ?></a>
                    </div>
                </div>
                <div class="block box-content-col">
                    <div class="block-title">
                        <?= $block->escapeHtml(__('Email')) ?>
                    </div>
                    <div class="block-title">
                        <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?>
                    </div>
                    <div class="block-edit">
                        <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>"><?= $block->escapeHtml(__('Edit')) ?></a>
                    </div>
                </div>
                <div class="block box-content-col">
                    <div class="block-title">
                        <?= $block->escapeHtml(__('Password')) ?>
                    </div>
                    <div class="block-title">
                        <?= $block->escapeHtml(__('*************')) ?>
                    </div>
                    <div class="block-edit">
                        <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>"><?= $block->escapeHtml(__('Edit')) ?></a>
                    </div>
                </div>
                <div class="block box-content-col">
                    <div class="block-title">
                        <?= $block->escapeHtml(__('Date of birth')) ?>
                    </div>
                    <div class="block-title">
                        <?= $block->getCustomer()->getDob() ? $block->escapeHtml($block->getCustomer()->getDob()) : '-' ?>
                    </div>
                    <div class="block-edit">
                        <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>"><?= $block->escapeHtml(__('Edit')) ?></a>
                    </div></a>
                </div>
                <!-- <?= $block->getChildHtml('customer.account.dashboard.info.extra'); ?> -->
            </div>
            <div class="box-actions find-more-btn">
                <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('FIND OUT MORE')) ?></span>
                </a>
                <!-- <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a> -->
            </div>
        </div>
        <?php if ($block->isNewsletterEnabled()) : ?>
            <!-- <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()) : ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else : ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>">
                        <span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div> -->
        <?php endif; ?>
        <?= $block->getChildHtml('additional_blocks'); ?>
    </div>
</div>