version: "3"
services:

  devtools:
    build: ./devtools
    volumes:
      - ../:${DESTINATION_PATH}/
      - ~/.npm:/var/www/.npm
      - ~/.nvm:/var/www/.nvm
      - ~/.composer:/var/www/.composer
    networks:
      - default
      - mysql
    environment:
      XDEBUG_CONFIG: "${XDEBUG_CONFIG_DEVTOOLS}"
      PHP_IDE_CONFIG: "${PHP_IDE_CONFIG}"

  fpm:
    build: ./fpm
    volumes:
      - ../:${DESTINATION_PATH}/
      - ~/.composer:/var/www/.composer
      - git:${DESTINATION_PATH}/.git
    networks:
      - default
      - mysql
    environment:
      XDEBUG_CONFIG: "${XDEBUG_CONFIG_FPM}"
      PHP_IDE_CONFIG: "${PHP_IDE_CONFIG}"

  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - fpm
    volumes:
      - ../:${DESTINATION_PATH}/
      - git:${DESTINATION_PATH}/.git
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      devbox:
      default:
        aliases:
          - nextouch_nginx

  elasticsearch:
  # if this service dies due to an error "max virtual memory areas vm.max_map_count [65530] is too low" run "$ sudo sysctl -w vm.max_map_count=262144" on the host machine
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - discovery.type=single-node
    #    ulimits:
    #      nofile:
    #        soft: 65536
    #        hard: 65536
    networks:
      - default
      - devbox

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    networks:
      - default
      - devbox

  varnish:
    depends_on:
      - nginx
    build: ./varnish/
    volumes:
      - ./varnish/default.vcl:/etc/varnish/default.vcl
    #        - ./varnish/varnish.secret:/etc/varnish/secret
    #      environment:
    #       - CACHE_SIZE=256M
    environment:
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
      VIRTUAL_PORT: "${VIRTUAL_PORT}"
    networks:
      - default
      - devbox
  rabbitmq:
    image: rabbitmq:3.8.6-management
    ports:
    - 5672:5672
    - 15672:15672
    environment:
      RABBITMQ_VM_MEMORY_HIGH_WATERMARK: 1024MiB
      RABBITMQ_DEFAULT_USER: "${RABBITMQ_USER}"
      RABBITMQ_DEFAULT_PASS: "${RABBITMQ_PASS}"
    networks:
      - default
      - devbox
  redis:
    image: redis
    networks:
      default:
        aliases:
          - redishost

networks:
  default:

  devbox:
    external: true

  mysql:
    external: true

volumes:
  git:
