<?php
/**
 * @see \Axepta\Paymentservice\Block\Adminhtml\System\Config\Source\LogDateRangeBtn
 * @var \Axepta\Paymentservice\Block\Adminhtml\System\Config\Source\LogDateRangeBtn $block
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $objectManager->get('\Axepta\Paymentservice\Helper\Data');
$locale = $objectManager->get('\Magento\Framework\Stdlib\DateTime\TimezoneInterface');
$format = $locale->getDateFormat(IntlDateFormatter::SHORT);

$date_from = new \Zend\Form\Element\Date();
$date_from->setName('log_date_range_from');
$date_from->setAttribute('id', 'log_date_range_from');
$date_from->setAttribute('image', $this->getSkinUrl('images/grid-cal.gif'));
$date_from->setValue($this->getValue(), $format);
$date_from->setFormat($format);

$url = $block->getUrl('axepta/log/index');
$url = rtrim($url, '/');
?>
<?php ?>
<input type="hidden" id="log_date_url" value="<?php echo $url ?>">
<button
        id="axepta_log_dowload_btn"
        type="button"
        class="button"
        style="width: 280px;">
    <span><?php echo $block->escapeHtml(__('Download')); ?></span>
</button>

