<?php /** @var $block Toolbar */

use Magento\Catalog\Block\Product\ProductList\Toolbar;
use Magento\Framework\Json\Helper\Data;

?>

<?php if ($block->getCollection()->getSize()) :?>
    <?php $widget = $this->helper(Data::class)->jsonDecode($block->getWidgetOptionsJson());
        $widgetOptions = $this->helper(Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= $widgetOptions; ?>}'>
        <?php if ($block->getIsBottom()): ?>
            <?= $block->getPagerHtml(); ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')); ?>
        <?php else: ?>
            <div class="row">
                <div class="col-12 col-sm-6 mb-4 mb-lg-0">
                    <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/info.phtml')); ?>
                </div>

                <div class="col-12 col-sm-6">
                    <?php if ($block->isExpanded()): ?>
                        <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')); ?>
                    <?php endif ?>
                </div>
            </div>
        <?php endif ?>
    </div>
<?php endif ?>
