<?php

/** @var \Nextouch\GestLogis\Block\Postcode $block */

?>

<?php $helperData     = $block->dataHelperObj(); ?>
<?php $shippingActive = $helperData->isShippingActive(); ?>

<?php if ($shippingActive) : ?>
    <?php $postcode = $helperData->getPostcodeFromSession(); ?>
    <?php $saveShippingPriceAjaxUrl = $block->getSaveShippingPriceAjaxUrl(); ?>
    <?php $attributeSetId = $block->getAttributeSetId(); ?>
    <?php $productId = $block->getProductId(); ?>

    <div id="postcode-modal-content">
        <div class="postcode-content">
            <p class="middle-desc"><?= __('Enter your zip code to check coverage for additional services'); ?></p>
            <div class="postcode-checker">
                <input type="text" class="postcode-input-checker" placeholder="<?= __('Enter your postcode'); ?>" value="<?= $postcode; ?>" />
                <p><?= __('for example. '); ?><?= "44100"; ?></p>
                <p class="availability-validation"></p>
            </div>
            <div class="button-section">
                <button class="check-postcode-btn" disabled><?= __('Check'); ?></button>
                <button class="reset-postcode-btn"><?= __('Reset'); ?></button>
            </div>
        </div>
    </div>

    <script type="text/javascript">
        require(['jquery', 'postcode-modal'], function($, PostcodeModal) {
            window.saveShippingPriceAjaxUrl = '<?= $saveShippingPriceAjaxUrl ?>';
            window.attributeSetId = '<?= $attributeSetId ?>';
            window.productId = '<?= $productId ?>';

            var config = {
                target: "#postcode-modal-content"
            };
            PostcodeModal.initModal(config);

            
            $(document).on('click', '.postcode-content button.reset-postcode-btn', function() {
                console.log('clicked');
                localStorage.removeItem("postcodeState");
                postcode = '';
                var formKey = $("input[name=form_key]").val();

                var attributeSetId = window.attributeSetId;
                var productId = window.productId;
                $.ajax({
                    url: window.saveShippingPriceAjaxUrl,
                    showLoader: true,
                    data: {
                        form_key: formKey,
                        postcode: postcode,
                        attribute_set_id: attributeSetId,
                        product_id: productId
                    },
                    dataType: 'json',
                    success: function (response) {
                        location.reload();
                    }
                });
            });

            /* if (localStorage.getItem("postcodeState") != "shown") {
                // Remove the whole section if postcode modal shown
                //$('.gestlogis-postcode-product').remove();

                // Unset postcode from session
                var formKey = $("input[name=form_key]").val();
                $.ajax({
                    url: window.saveShippingPriceAjaxUrl,
                    showLoader: true,
                    data: {
                        form_key: formKey,
                        postcode: 0,
                    },
                    dataType: 'json',
                    success: function(response) {
                        if (response.success == true) {
                            // Do Nothing.
                        }
                    }
                });
            } */
        });
    </script>
<?php endif; ?>