<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<?php if ($block->getCollection()->getSize()) :?>
    <?php $widget = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonDecode($block->getWidgetOptionsJson());
    $widgetOptions = $this->helper(\Magento\Framework\Json\Helper\Data::class)->jsonEncode($widget['productListToolbarForm']);
    ?>
    <div class="toolbar toolbar-products" data-mage-init='{"productListToolbarForm":<?= /* @noEscape */ $widgetOptions ?>}'>
        <?php if ($block->getIsBottom()): ?>
            <?= $block->getPagerHtml() ?>
            <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
        <?php else: ?>
        <div class="category-info-top">
            <?php echo $block->getChildHtml('category.info.top') ?>
        </div>

        <span class="open-compare-mobile-container" data-bind="scope: 'compareProducts'">
            <span class="open-compare-mobile"><?= __('Compare') ?></span>
        </span>
        <div class="toolbar-options">

            <span class="open-filter-mobile"><?= __('Filters') ?></span>
            <?php if ($block->isExpanded()): ?>
                <?php // $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
            <?php endif ?>
            <?php // $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
            <?php if ($block->isExpanded()): ?>
                <?= $block->fetchView($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter-custom.phtml')) ?>
            <?php endif ?>
        </div>
        <?php endif ?>
        <?php if (!$block->getIsBottom()): ?>
            <?= $block->getChildHtml('catalog.compare.sidebar') ?>
        <?php endif; ?>
    </div>
<?php endif ?>


