<?php /** @var \Magento\Theme\Block\Html\Footer $block */ ?>
<div class="row justify-content-between">
    <div class="col-4">
        <span><?= $block->escapeHtml($block->getCopyright()); ?></span>
    </div>

    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/visa.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/verified-by-visa.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/mastercard.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/mastercard-securecode.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/american-express.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/safekey.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/apple-pay.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/paypal.svg'); ?>" width="50" alt=""/>
    </div>
    <div class="col-auto">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/findomestic.svg'); ?>" width="50" alt=""/>
    </div>
</div>
