<?php /** @var \Magento\Theme\Block\Html\Footer $block */ ?>
<div class="footer-copyright">
    <div class="text-copyright">
        <span><?= $block->escapeHtml($block->getCopyright()); ?></span>
    </div>

    <div class="payments-icon">
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/visa.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/verified-by-visa.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/mastercard.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/mastercard-securecode.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/american-express.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/safekey.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/apple-pay.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/paypal.png'); ?>" width="50" alt=""/>
        </div>
        <div class="col-auto">
            <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/findomestic.png'); ?>" width="50" alt=""/>
        </div>
    </div>
</div>
