<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="col-auto">
    <a href="https://facebook.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/facebook.png'); ?>" width="50" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https://instagram.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/instagram.png'); ?>" width="50" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https://twitter.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/twitter.png'); ?>" width="50" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https://linkedin.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/linkedin.png'); ?>" width="50" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https://youtube.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/youtube.png'); ?>" width="50" alt=""/>
    </a>
</div>
