<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/facebook.png'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/instagram.png'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/twitter.png'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/linkedin.png'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('Magento_Theme::images/social/youtube.png'); ?>" width="30" alt=""/>
    </a>
</div>
