<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('images/facebook.svg'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('images/instagram.svg'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('images/twitter.svg'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('images/linkedin.svg'); ?>" width="30" alt=""/>
    </a>
</div>

<div class="col-auto">
    <a href="https//www.example.com" target="_blank">
        <img src="<?= $block->getViewFileUrl('images/youtube.svg'); ?>" width="30" alt=""/>
    </a>
</div>
