<?php
/* @var \Magento\Catalog\Block\Product\View\AbstractView $block */

$_product = $block->getProduct();
?>

<?php if ($block->displayProductStockStatus()) : ?>
    <?php if ($_product->isAvailable()) : ?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')); ?>">
            <i class="fas fa-circle fa-lg text-primary"></i>
            <span><?= $block->escapeHtml(__('In stock')); ?></span>
        </div>
    <?php else : ?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')); ?>">
            <i class="fas fa-circle fa-lg text-danger"></i>
            <span><?= $block->escapeHtml(__('Out of stock')); ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
