<?php /** @var \Magento\LayeredNavigation\Block\Navigation $block */ ?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
        <span class="close-filter-mobile"></span>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
        <div class="block-title filter-title" data-count="<?= $filtered; ?>">
            <strong data-role="title"><?= $block->escapeHtml(__('Filters')); ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()); ?>" class="action clear filter-clear">
                        <span><?= $block->escapeHtml(__('Clear All')); ?></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php $i = 0; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php $i++; ?>
                <?php $isProductAttribute = $filter instanceof \Amasty\Shopby\Model\Layer\Filter\Attribute; ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')); ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "multipleCollapsible": false
                            }
                        }'>
                        <?php $wrapOptions = true;
                        endif; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title">
                            <?= $block->escapeHtml(__($filter->getName())); ?>

                            <?php if ($isProductAttribute && $filter->getAttributeModel()->getAttributeExplanation()): ?>
                                <div class="filter-popup-content" data-bind="mageInit: {
                                    'Magento_Ui/js/modal/modal':{
                                        'type': 'popup',
                                        'modalClass':'modalfilter',
                                        'parentModalClass':'modalfilter',
                                        'title': '<?= $block->escapeHtml(__($filter->getName())); ?>',
                                        'trigger': '[data-trigger=trigger<?= $i ?>]',
                                        'responsive': true,
                                        'zIndex': '898',
                                        'buttons': false
                                    }}">
                                    <div class="content">
                                        <?= $filter->getAttributeModel()->getAttributeExplanation(); ?>
                                    </div>
                                </div>
                                <span class="info-icon" data-trigger="trigger<?= $i ?>"></span>
                            <?php endif; ?>
                        </div>
                        <div data-role="content" class="filter-options-content">
                            <?= $block->getChildBlock('renderer')->render($filter); ?>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </div>
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>

