<?php /** @var \Magento\Checkout\Block\Onepage\Success $block */ ?>

<!-- TODO: Change placeholder texts -->
<?php if ($block->getOrderId()) : ?>
    <div class="checkout-success">

        <h2><?= __('ORDINE EFFETTUATO, GRAZIE!') ?></h2>

        <p>
            <?= __(
                "Siamo felici di averti come cliente e siamo qui per offrirti un'esperienza di shopping eccezionale. La tua fiducia in noi è molto importante, e ci impegniamo a fornirti prodotti di alta qualità e un servizio clienti impeccabile."
            ) ?>
        </p>
        <br>

        <p>
            <?= __(
                "Se hai bisogno di ulteriori informazioni o hai domande specifiche riguardo al tuo ordine, non esitare a contattarci. Il nostro team di assistenza clienti sarà lieto di fornirti tutto il supporto necessario. Siamo qui per garantire che tu abbia un'esperienza di acquisto piacevole e senza stress."
            ) ?>
        </p>

        <div class="checkout-success__icons">
            <div class="checkout-success__icon">
                <img src="<?= $block->getViewFileUrl('Magento_Checkout::images/checkout/echo_choice_icon.png') ?>"/>
                <p><?= __("Il trasporto ed il packaging del tuo ordine sono green.") ?></p>
            </div>

            <div class="checkout-success__icon">
                <img src="<?= $block->getViewFileUrl('Magento_Checkout::images/checkout/location_icon.png') ?>"/>
                <p><?= __("Traccia il tuo ordine in ogni momento.") ?></p>
            </div>
        </div>
    </div>
<?php endif; ?>

<script>
    require(['jquery', 'jquery/jquery.cookie'], function ($) {
        $.cookie('default_payment_method', null, {path: '/'});
    });
</script>
