<?php /** @var \Magento\Framework\View\Element\Template $block */ ?>
<div class="d-flex flex-sm-column justify-content-space-between m-b-sm">
    <div class="d-flex flex-column">
        <div class="order-sm-2">
            <label class="text-h4"><?= $block->escapeHtml(__('We ship with')) ?></label>
            <ul>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/shippings/dhl.png'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/shippings/gls.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/shippings/fastest.png'); ?>" alt=""/>
                </li>
            </ul>
        </div>

        
    </div>

    <div class="d-flex flex-wrap">
        <div>
            <label class="text-h4"><?= $block->escapeHtml(__('Payment methods')) ?></label>
            <ul>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/mastercard.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/visa.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/paypal.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/findomestic.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/maestro.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/mastercard-secure.svg'); ?>"
                         alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/verified-visa.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/postepay.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/visa-electron.svg'); ?>" alt=""/>
                </li>
                <li>
                    <img src="<?= $block->getViewFileUrl('Magento_Theme::images/payments/american-express.svg'); ?>" alt=""/>
                </li>
            </ul>
        </div>
    </div>
</div>
