<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Info $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>
<strong class="product-item-name">
    <a href="<?= $block->escapeUrl($block->getProductUrl($item)) ?>" title="<?= $block->escapeHtmlAttr($product->getName()) ?>" class="product-item-link">
        <?= $block->escapeHtml($product->getName()) ?>
    </a>
</strong>
<div class="product-short-info"> <?= strlen($product->getShortDescription()) > 200 ? substr($product->getShortDescription(), 0, 200) . '...' :  $product->getShortDescription() ?> </div>
