<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Cart $block */
?>
<div class="product-price-box">
<?php foreach ($block->getChildNames() as $childName) : ?>
    <?= /* @noEscape */ $block->getLayout()->renderElement($childName, false) ?>
<?php endforeach; ?>

<?php
$product = $block->getProductItem();
$price = $product->getPrice();
$finalPrice = $product->getFinalPrice();
$savingPercent = 0;
if ($product->getTypeId() !== 'simple') {
    $children = $product->getTypeInstance()->getUsedProducts($product);
    $price = search(fn (\Magento\Catalog\Model\Product $item) => $item->getPrice(), $children);
}

if ($finalPrice < $price) {
    $savingPercent = 100 - round(($finalPrice / $price) * 100);
}
?>

<?php if ($savingPercent > 0) : ?>
    <span class="saving-percent">
        <?= __('Savings') ?> <br>
        <strong><?= sprintf('%s%%', $savingPercent); ?></strong>
    </span>
<?php endif; ?>

</div>