<?php

use Magento\Framework\App\Action\Action;
use Nextouch\Catalog\Api\Data\ProductInterface;

/**
 * Product list template
 *
 * @var \Nextouch\Theme\Block\Catalog\Product\ListProduct $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */
$_productCollection = $block->getLoadedProductCollection();
/** @var \Magento\Catalog\Helper\Output $_helper */
$_helper = $block->getData('outputHelper');
?>

<?php if (!$_productCollection->count()): ?>
    <div class="message info empty">
        <div><?= $escaper->escapeHtml(__('We can\'t find products matching the selection.')) ?></div>
    </div>
<?php else: ?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() === 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="for-mobile category-page-title">
        <?php echo $this->getLayout()->createBlock("Magento\Theme\Block\Html\Title")->setTemplate("Magento_Theme::html/title.phtml")->toHtml() ?>
    </div>
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $index => $_product):
                $savingPercent = $block->getSavingPercent($_product);
                $isRecommended = (bool) $_product->getData(ProductInterface::IS_RECOMMENDED);
                $changeTopLeftBorder = $isRecommended || $savingPercent > 0;
            ?>
            <li class="item product product-item">
                <div class="product-item-info"
                     id="product-item-info_<?= /* @noEscape */ $_product->getId() ?>"
                     data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = 'left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;';
                    }
                    ?>
                    <?php // Product Image ?>
                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?php if ($savingPercent > 0): ?>
                            <span class="product-item-badge product-item-badge--on-sale">
                               <?= __('Save up on -%1%', $savingPercent); ?>
                            </span>
                        <?php elseif ($isRecommended): ?>
                            <span class="product-item-badge product-item-badge--recommended">
                                <?= __('Recommended'); ?>
                            </span>
                        <?php endif; ?>
                        <?= $productImage->toHtml() ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php $_productNameStripped = $block->stripTags($_product->getName(), null, true); ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>">
                                <?=/* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name')?>
                            </a>
                        </strong>
                        <?php /* <div class="product-short-info"> <?= /* @noEscape * / $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></div> */?> 
                       
                        <?php        
                            $attributeSetId = $_product->getAttributeSetId(); ?>
                            <?php if(in_array($attributeSetId, [985, 986, 987])) : ?>
                                <?php  
                                    $wins2535 = $_product->getResource()->getAttribute('wins_2535')->getFrontend()->getValue($_product);
                                    $wins9551 = $_product->getResource()->getAttribute('wins_9551')->getFrontend()->getValue($_product);
                                    $wins10372 = $_product->getResource()->getAttribute('wins_10372')->getFrontend()->getValue($_product);
                                    $wins11013 = $_product->getResource()->getAttribute('wins_11013')->getFrontend()->getValue($_product);
                                    $wins11195 = $_product->getResource()->getAttribute('wins_11195')->getFrontend()->getValue($_product);
                                ?>
                                <div class="card-attribute-list"> 
                                    <?php if($wins2535) : ?> <span class="card-attribute-item"> <?= __('Dimensioni schermo (pollici)') ?> <?= $wins2535 ?></span><?php endif; ?>
                                    <?php if($wins9551) : ?> <span class="card-attribute-item"> <?= __('Tipologia dello schermo') ?> <?= $wins9551 ?></span><?php endif; ?>
                                    <?php if($wins10372) : ?> <span class="card-attribute-item"> <?= __('Risoluzione') ?> <?= $wins10372 ?></span><?php endif; ?>
                                    <?php if($wins11013) : ?> <span class="card-attribute-item"> <?= __('Smart Tv') ?> <?= $wins11013 ?></span><?php endif; ?>
                                    <?php if($wins11195) : ?> <span class="card-attribute-item"> <?= __('HDR') ?> <?= $wins11195 ?></span><?php endif; ?>
                                </div>
                            <?php elseif($attributeSetId == 979): ?>
                                <?php  
                                    $wins6115 = $_product->getResource()->getAttribute('wins_6115')->getFrontend()->getValue($_product);
                                    $wins9427 = $_product->getResource()->getAttribute('wins_9427')->getFrontend()->getValue($_product);
                                    $wins11028 = $_product->getResource()->getAttribute('wins_11028')->getFrontend()->getValue($_product);
                                    $wins8160 = $_product->getResource()->getAttribute('wins_8160')->getFrontend()->getValue($_product);
                                    $wins5315 = $_product->getResource()->getAttribute('wins_5315')->getFrontend()->getValue($_product);
                                ?>
                                <div class="attribute-list"> 
                                    <?php if($wins6115) : ?> <span class="card-attribute-item"> <?= __('Risoluzione') ?> <?= $wins6115 ?></span><?php endif; ?>
                                    <?php if($wins9427) : ?> <span class="card-attribute-item"> <?= __('Tecnologia') ?> <?= $wins9427 ?></span><?php endif; ?>
                                    <?php if($wins11028) : ?> <span class="card-attribute-item"> <?= __('3D') ?> <?= $wins11028 ?></span><?php endif; ?>
                                    <?php if($wins8160) : ?> <span class="card-attribute-item"> <?= __('Wireless') ?> <?= $wins8160 ?></span><?php endif; ?>
                                    <?php if($wins5315) : ?> <span class="card-attribute-item"> <?= __('Posizionamento apparecchio') ?> <?= $wins5315 ?></span><?php endif; ?>
                                </div>
                            <?php endif; ?>
                    
                        <?php $review =  $block->getReviewsSummaryHtml($_product, $templateType) ?>
                        <?php if($review): ?>
                        <?= $review; ?>
                        <?php else: ?>
                            <div class="product-reviews-summary short">
                                <div class="rating-summary rating-empty">
                                    <div class="rating-result"></div>
                                </div>
                                <div class="reviews-actions">
                                    <span class="view">
                                        0
                                        <span><?= __('Reviews') ?></span>
                                    </span>
                                </div>
                            </div>
                        <?php endif; ?>
                        <div class="price-review-column">                           
                            <?php if ($savingPercent > 0): ?>
                                <span class="saving-percent">
                                        <?= __('Savings') ?> <br>
                                        <strong><?= sprintf('%s%%', $savingPercent); ?></strong>
                                        <!-- <?= sprintf('-%s%%', $savingPercent); ?> -->
                                    </span>
                            <?php endif; ?>
                            <div class="product-item-prices">
                                <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                <span class="tax-included"><?= __('Tax included') ?></span>
                            </div>
                        </div>

                        
                        <?= strpos($pos, $viewMode . '-secondary') ?
                            /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                $position,
                                'product-item-info_' . $_product->getId() . ' div.actions-secondary'
                            ) : '' ?>


                        <?= $block->getProductDetailsHtml($_product) ?>

                        <div class="product-item-inner">
                            <div data-role="add-to-links" class="actions-secondary">
                                <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                    <?= $addToBlock->setProduct($_product)->getChildHtml() ?>
                                <?php endif; ?>
                            </div>
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()):?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <form data-role="tocart-form"
                                              data-product-sku="<?= $escaper->escapeHtml($_product->getSku()) ?>"
                                              action="<?= $escaper->escapeUrl($postParams['action']) ?>"
                                              method="post">
                                            <?php $optionsData = $block->getData('viewModel')->getOptionsData($_product); ?>
                                            <?php foreach ($optionsData as $optionItem): ?>
                                                <input type="hidden"
                                                       name="<?= $escaper->escapeHtml($optionItem['name']) ?>"
                                                       value="<?= $escaper->escapeHtml($optionItem['value']) ?>">
                                            <?php endforeach; ?>
                                            <input type="hidden"
                                                   name="product"
                                                   value="<?= /* @noEscape */ $postParams['data']['product'] ?>">
                                            <input type="hidden"
                                                   name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>"
                                                   value="<?=
                                                   /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED]
                                                    ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $escaper->escapeHtmlAttr(__('Add to Cart')) ?>"
                                                    class="action tocart primary"
                                                    disabled>
                                                <span><?= $escaper->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else:?>
                                        <?php if ($_product->isAvailable()):?>
                                            <div class="stock available">
                                                <span><?= $escaper->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else:?>
                                            <div class="stock unavailable">
                                                <span><?= $escaper->escapeHtml(__('Out of stocks')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <?= strpos($pos, $viewMode . '-primary') ?
                                    /* @noEscape */ $secureRenderer->renderStyleAsTag(
                                        $position,
                                        'product-item-info_' . $_product->getId() . ' div.actions-primary'
                                    ) : '' ?>

                            </div>
                            <?php if ($showDescription): ?>
                                <div class="product description product-item-description">
                                    <?= /* @noEscape */ $_helper->productAttribute(
                                        $_product,
                                        $_product->getShortDescription(),
                                        'short_description'
                                    ) ?>
                                    <a href="<?= $escaper->escapeUrl($_product->getProductUrl()) ?>"
                                       title="<?= /* @noEscape */ $_productNameStripped ?>"
                                       class="action more"><?= $escaper->escapeHtml(__('Learn More')) ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?= strpos($pos, $viewMode . '-actions') ?
                /* @noEscape */ $secureRenderer->renderStyleAsTag(
                    $position,
                    'product-item-info_' . $_product->getId() . ' div.product-item-actions'
                ) : '' ?>
            </li>
            <?php endforeach; ?>
        </ol>
    </div>
    <?= $block->getChildBlock('toolbar')->setIsBottom(true)->toHtml() ?>
    <script type="text/x-magento-init">
    {
        "[data-role=tocart-form], .form.map.checkout": {
            "catalogAddToCart": {
                "product_sku": "<?= $escaper->escapeJs($_product->getSku()) ?>"
            }
        }
    }
    </script>
<?php endif; ?>

<script type="text/javascript">
    require(['jquery'], function ($) {
        $(document).ready(function () {
            if($('.sidebar #layered-filter-block').length) {
                $('.open-filter-mobile').addClass('visible').on('click', function () {
                    document.body.scrollTop = document.documentElement.scrollTop = 0;
                    $('.sidebar #layered-filter-block').addClass('active').addClass('show');
                    $('body').addClass('filter-mobile-opened');
                });
                $('.close-filter-mobile').on('click', function () {
                    $('.sidebar #layered-filter-block').removeClass('active').removeClass('show');
                    $('body').removeClass('filter-mobile-opened');
                });
            }
        });
    });
</script>
