<?php /* @var \Magento\Catalog\Block\Product\View\AbstractView $block */

use Nextouch\Catalog\Api\Data\ProductInterface; ?>
<?php $_product = $block->getProduct() ?>

<?php if ($block->displayProductStockStatus()) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stocks')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>

<?php if ($_product->getData(ProductInterface::IS_PICKUPABLE)) :?>
    <?php if ($_product->isAvailable()) :?>
        <div class="stock available" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('In stock for pick and pay')) ?></span>
        </div>
    <?php else :?>
        <div class="stock unavailable" title="<?= $block->escapeHtmlAttr(__('Availability')) ?>">
            <span><?= $block->escapeHtml(__('Out of stock for pick and pay')) ?></span>
        </div>
    <?php endif; ?>
<?php endif; ?>
