<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Magento2.Files.LineLength.MaxExceeded

/** @var $block \Nextouch\Theme\Block\Checkout\Cart\Item\Renderer */

$_item = $block->getItem();
$product = $_item->getProduct();
$isVisibleProduct = $product->isVisibleInSiteVisibility();
/** @var \Magento\Msrp\Helper\Data $helper */
$helper = $this->helper(Magento\Msrp\Helper\Data::class);
$canApplyMsrp = $helper->isShowBeforeOrderConfirm($product) && $helper->isMinimalPriceLessMsrp($product);
$_services = $block->getFormattedServiceList();
?>
<div class="cart item">
    <div class="item-info">
        <div class="item-info-left">
            <div data-th="<?= $block->escapeHtml(__('Item')) ?>" class="col item">
                <?php if ($block->hasProductUrl()) :?>
                    <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"
                       title="<?= $block->escapeHtml($block->getProductName()) ?>"
                       tabindex="-1"
                       class="product-item-photo">
                <?php else :?>
                    <span class="product-item-photo">
                <?php endif;?>
                <?= $block->getImage($block->getProductForThumbnail(), 'cart_page_product_thumbnail')->toHtml() ?>
                <?php if ($block->hasProductUrl()) :?>
                    </a>
                <?php else :?>
                    </span>
                <?php endif; ?>
                <div class="product-item-details">
                    <strong class="product-item-name">
                        <?php if ($block->hasProductUrl()) :?>
                            <a href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml($block->getProductName()) ?></a>
                        <?php else :?>
                            <?= $block->escapeHtml($block->getProductName()) ?>
                        <?php endif; ?>
                    </strong>
                    <?php if ($messages = $block->getMessages()) :?>
                        <?php foreach ($messages as $message) :?>
                            <div class= "cart item message <?= $block->escapeHtmlAttr($message['type']) ?>">
                                <div><?= $block->escapeHtml($message['text']) ?></div>
                            </div>
                        <?php endforeach; ?>
                    <?php endif; ?>
                    <?php $addInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
                    <?php if ($addInfoBlock) :?>
                        <?= $addInfoBlock->setItem($_item)->toHtml() ?>
                    <?php endif;?>


                    <?php if ($canApplyMsrp) :?>
                        <div class="col msrp" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                    <span class="pricing msrp">
                        <span class="msrp notice"><?= $block->escapeHtml(__('See price before order confirmation.')) ?></span>
                        <?php $helpLinkId = 'cart-msrp-help-' . $_item->getId(); ?>
                        <a href="#" class="action help map"
                           id="<?= ($block->escapeHtmlAttr($helpLinkId)) ?>"
                           data-mage-init='{"addToCart":{
                                                "helpLinkId": "#<?= $block->escapeJs($block->escapeHtml($helpLinkId)) ?>",
                                                "productName": "<?= $block->escapeJs($block->escapeHtml($product->getName())) ?>",
                                                "showAddToCart": false
                                                }
                                            }'
                        >
                            <span><?= $block->escapeHtml(__("What's this?")) ?></span>
                        </a>
                    </span>
                        </div>
                    <?php else :?>
                        <div class="col price" data-th="<?= $block->escapeHtml(__('Price')) ?>">
                            <?= $block->getUnitPriceHtml($_item) ?>

                            <?php if ($block->hasSpecialPrice()): ?>
                                <span class="old-price">
                                    <?= /* @noEscape */ $block->renderAmount(\Magento\Catalog\Pricing\Price\RegularPrice::PRICE_CODE, [
                                        'price_type'        => 'oldPrice',
                                        'include_container' => true,
                                        'skip_adjustments'  => true
                                    ]); ?>
                                </span>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>

                    <a class="see-details" href="<?= $block->escapeUrl($block->getProductUrl()) ?>"><?= $block->escapeHtml(__('See Product Details')) ?></a>

                    <div class="col qty" data-th="<?= $block->escapeHtml(__('Qty')) ?>">
                        <div class="field qty">
                            <div class="actions-toolbar">
                                <?= /* @noEscape */ $block->getActions($_item) ?>
                            </div>
                            <div class="control qty">
                                <?php if ($block->getQty() > 1): ?>
                                    <span class="more-less less-button"></span>
                                <?php endif; ?>
                                <label for="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty">
                                    <span class="label"><?= $block->escapeHtml(__('Qty')) ?></span>
                                    <input id="cart-<?= $block->escapeHtmlAttr($_item->getId()) ?>-qty"
                                           name="cart[<?= $block->escapeHtmlAttr($_item->getId()) ?>][qty]"
                                           data-cart-item-id="<?= $block->escapeHtmlAttr($_item->getSku()) ?>"
                                           value="<?= $block->escapeHtmlAttr($block->getQty()) ?>"
                                           type="number"
                                           size="4"
                                           step="any"
                                           title="<?= $block->escapeHtmlAttr(__('Qty')) ?>"
                                           class="input-text qty"
                                           data-validate="{required:true,'validate-greater-than-zero':true}"
                                           data-role="cart-item-qty"/>
                                </label>

                                <span class="more-less more-button"></span>
                            </div>
                        </div>
                    </div>


                </div>
            </div>

        </div>
        <div class="item-options-container">
            <?php if ($_services) : ?>
                <dl class="item-options">
                    <?php foreach ($_services as $_service): ?>
                        <dd>
                            <a href="#"
                               class="action"
                               title="<?= __('Remove Service'); ?>"
                               aria-label="<?= __('Remove Service'); ?>"
                               data-post='<?= $block->getRemoveServicePostDataParams($_service); ?>'
                               role="button">
                                <span class="material-icons">close</span>
                            </a>
                            <span class="info">
                                <?= $block->escapeHtml($_service['serviceLabel'], ['span', 'a']) ?>
                            </span>
                        </dd>
                    <?php endforeach; ?>
                </dl>
            <?php endif; ?>
            <div class="col subtotal" data-th="<?= $block->escapeHtml(__('Subtotal')) ?>">
                <?php if ($canApplyMsrp) :?>
                    <span class="cart msrp subtotal">--</span>
                <?php else :?>
                    <?= $block->getRowTotalHtml($_item) ?>
                <?php endif; ?>
            </div>
        </div>
    </div>

    <div class="item-actions">
        <div colspan="4">
            <div class="actions-toolbar">
                <?= /* @noEscape */ $block->getActions($_item) ?>
            </div>
        </div>
    </div>
</div>

<script>
    require(['jquery'], function ($) {
        $('.more-less').click(function () {
            $('#form-validate').submit();
        })
    });
</script>
