<?php
/** @var \Magento\Catalog\Block\Product\View $block */

$_product = $block->getProduct();
$body = __('I%20want%20to%20recommend%20this%20product%20on%20Nextouch%0A%0AMore%20information%3A%20');
?>

<?php if ($block->canEmailToFriend()) : ?>
    <a href="mailto:?body=<?= $body . $_product->getProductUrl(); ?>" class="action mailto">
        <i class="fas fa-share-alt fa-3x text-primary"></i>
    </a>
<?php endif; ?>
