version: 0.2
phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
    build:
        commands:
            - echo Build started on `date`
            - ./kubernetes/build/build-images.sh nextouch $CODEBUILD_RESOLVED_SOURCE_VERSION production $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/k8s-prd $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/k8s-prd/nextouch-code:nextouch-$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/k8s-prd/nextouch-nginxws:nextouch-$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/k8s-prd/nextouch-php-fpm:nextouch-$CODEBUILD_RESOLVED_SOURCE_VERSION
            - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/k8s-prd/nextouch-php-cli:nextouch-$CODEBUILD_RESOLVED_SOURCE_VERSION
    post_build:
        commands:
            - echo Build completed on `date`
cache:
    paths:
        - '/root/bin/*'
