<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Generic.Files.LineLength.TooLong

/** @var \Magento\Customer\Block\Form\Login $block */
?>

<div class="columns-customer-login">

    <div class="col1 customer-login-left-block">
        <div class="block block-customer-login">
            <div class="block-title">
                <h2 id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Sign In')) ?></h2>
            </div>
            <div class="block-content" aria-labelledby="block-customer-login-heading">
                <form class="form form-login"
                      action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
                      method="post"
                      id="login-form"
                      data-mage-init='{"validation":{}}'>
                    <?= $block->getBlockHtml('formkey') ?>
                    <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                        <div class="field email required">
                            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                            <div class="control">
                                <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>"
                                       placeholder="<?= $block->escapeHtml(__('Email')) ?>"
                                    <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                                       id="email" type="email" class="input-text"
                                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                                       data-mage-init='{"mage/trim-input":{}}'
                                       data-validate="{required:true, 'validate-email':true}">
                            </div>
                        </div>
                        <div class="field password required">
                            <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                            <div class="control">
                                <input name="login[password]" type="password"
                                       placeholder="<?= $block->escapeHtml(__('Password')) ?>"
                                    <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?>
                                       class="input-text" id="pass"
                                       title="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                                       data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field choice" data-bind="scope: 'showPassword'">
                            <!-- ko template: getTemplate() --><!-- /ko -->
                        </div>
                        <?= $block->getChildHtml('form_additional_info') ?>

                            <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                            <div class="no-button">
                                <a href="<?= $block->escapeUrl($block->getCreateAccountUrl()) ?>" class="action create"><span><?= $block->escapeHtml(__('Register')) ?></span></a>
                            </div>


                            <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>

                    </fieldset>
                </form>
            </div>
            <script type="text/x-magento-init">
                {
                    "*": {
                        "Magento_Customer/js/block-submit-on-send": {
                            "formId": "login-form"
                        },
                        "Magento_Ui/js/core/app": {
                            "components": {
                                "showPassword": {
                                    "component": "Magento_Customer/js/show-password",
                                    "passwordSelector": "#pass"
                                }
                            }
                        }
                    }
                }
            </script>
        </div>
    </div>

    <div class="col2 customer-login-right-block">
        <?= $block->getChildHtml('customer.login.right.block') ?>
    </div>
</div>

