<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// phpcs:disable Magento2.Templates.ThisInTemplate

/** @var \Magento\CatalogWidget\Block\Product\ProductsList $block */
?>
<?php if ($exist = ($block->getProductCollection() && $block->getProductCollection()->getSize())) : ?>
    <?php
    $type = 'widget-product-carousel';

    $image = 'new_products_content_widget_grid';
    $items = $block->getProductCollection()->getItems();

    $showWishlist = true;
    $showCompare = true;
    $showCart = true;
    $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    ?>
    <ol class="product-items products-grid <?= /* @noEscape */ $type ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($items as $_item) : ?>
            <?php $savingPercent = $block->getSavingPercent($_item);
            $isRecommended = false; // TODO: implement interface
                //(bool) $_item->getData(ProductInterface::IS_RECOMMENDED);
            $changeTopLeftBorder = $isRecommended || $savingPercent > 0;
            ?>
            <?= /* @noEscape */ ($iterator++ == 1) ? '<li class="product-item">' : '</li><li class="product-item">' ?>
            <div class="product-item-info">
                <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product photo product-item-photo">
                    <?php if ($savingPercent > 0): ?>
                        <span class="product-item-badge product-item-badge--on-sale">
                               <?= __('Save up on -%1%', $savingPercent); ?>
                            </span>
                    <?php elseif ($isRecommended): ?>
                        <span class="product-item-badge product-item-badge--recommended">
                                <?= __('Recommended'); ?>
                            </span>
                    <?php endif; ?>

                    <?= $block->getImage($_item, $image)->toHtml() ?>
                </a>
                <div class="product details product-item-details">
                    <strong class="product-item-name">
                        <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                           href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                           class="product-item-link">
                            <?= $block->escapeHtml($_item->getName()) ?>
                        </a>
                    </strong>

                    <div class="product-short-info"> <?php // TODO: add subtext ?> </div>
                    <?php if ($templateType) : ?>
                        <?= $block->getReviewsSummaryHtml($_item, $templateType) ?>
                    <?php endif; ?>

                    <div class="product-item-prices">
                        <?= $block->getProductPriceHtml($_item, $type) ?>
                    </div>
                    <span class="tax-included"><?= __('Tax included') ?></span>

                    <?= $block->getProductDetailsHtml($_item) ?>

                    <?php if ($savingPercent > 0): ?>
                        <span class="saving-percent">
                                    <?= sprintf('-%s%%', $savingPercent); ?>
                                </span>
                    <?php endif; ?>

                    <?php if ($showWishlist || $showCompare) : ?>
                        <div class="actions-secondary" data-role="add-to-links">
                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist) : ?>
                                <a href="#"
                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                </a>
                            <?php endif; ?>
                            <?php if ($block->getAddToCompareUrl() && $showCompare) : ?>
                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                </a>
                            <?php endif; ?>
                        </div>
                    <?php endif; ?>

                    <div class="product-item-inner">
                        <div class="product actions product-item-actions">
                            <?php if ($showCart) : ?>
                                <div class="actions-primary">
                                    <?php if ($_item->isSaleable()) : ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_item); ?>
                                        <form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_item->getSku()) ?>" action="<?= $block->escapeUrl($postParams['action']) ?>" method="post">
                                            <input type="hidden" name="product" value="<?= $block->escapeHtmlAttr($postParams['data']['product']) ?>">
                                            <input type="hidden" name="<?= /* @noEscape */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @noEscape */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= $block->escapeHtml(__('Add to Cart')) ?></span>
                                            </button>
                                        </form>
                                    <?php else : ?>
                                        <?php if ($_item->getIsSalable()) : ?>
                                            <div class="stock available"><span><?= $block->escapeHtml(__('In stock')) ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= $block->escapeHtml(__('Out of stock')) ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                            <?php endif; ?>

                        </div>
                    </div>
                </div>
            </div>
            <?= ($iterator == count($items) + 1) ? '</li>' : '' ?>
        <?php endforeach ?>
    </ol>
<?php endif;?>
