<?php
/** @var \Magento\Contact\Block\ContactForm $block */
/** @var \Magento\Contact\ViewModel\UserDataProvider $viewModel */

$sideaConfig = $this->helper(Nextouch\Sidea\Helper\SideaConfig::class);
$viewModel = $block->getViewModel();
$contactFrequentQuestions = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('contact_frequent_questions');
$aboutServicesSlider = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_services_slider');
$aboutBanners = $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('about_banners');
?>
<form class="form contact"
      action="<?= $block->escapeUrl($sideaConfig->getContactActionUrl()) ?>"
      id="contact-form"
      method="post"
      data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
      data-mage-init='{"validation":{}}'>
    <?= $contactFrequentQuestions->toHtml() ?>

    <h2 class="text-h2"><?= $block->escapeHtml(__('Contact Us')) ?></h2>
    <fieldset class="fieldset">
        <input type=hidden name="orgid" value="<?= $block->escapeHtml($block->getContactOriginId()) ?>">
        <input type=hidden name="retURL" value="<?= $block->escapeUrl($block->getUrl('contact')) ?>">
        <div class="field name required">
            <label class="label" for="name"><span><?= $block->escapeHtml(__('Name')) ?></span></label>
            <div class="control">
                <input name="name"
                       id="name"
                       title="<?= $block->escapeHtmlAttr(__('Name')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserName()) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email required">
            <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
            <div class="control">
                <input name="email"
                       id="email"
                       title="<?= $block->escapeHtmlAttr(__('Email')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserEmail()) ?>"
                       class="input-text"
                       type="email"
                       data-validate="{required:true, 'validate-email':true}"/>
            </div>
        </div>
        <div class="field phone required">
            <label class="label" for="phone"><span><?= $block->escapeHtml(__('Phone Number')) ?></span></label>
            <div class="control">
                <input name="phone"
                       id="phone"
                       title="<?= $block->escapeHtmlAttr(__('Phone Number')) ?>"
                       value="<?= $block->escapeHtmlAttr($viewModel->getUserTelephone()) ?>"
                       class="input-text"
                       type="tel"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field subject required">
            <label class="label" for="subject"><span><?= $block->escapeHtml(__('Subject')) ?></span></label>
            <div class="control">
                <input name="subject"
                       id="subject"
                       title="<?= $block->escapeHtmlAttr(__('Subject')) ?>"
                       class="input-text"
                       type="text"
                       data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field description required">
            <label class="label" for="description">
                <span><?= $block->escapeHtml(__('What are you contacting us for?')) ?></span>
            </label>
            <div class="control">
                <textarea name="description"
                          id="description"
                          title="<?= $block->escapeHtmlAttr(__('What are you contacting us for?')) ?>"
                          class="input-text"
                          cols="5"
                          rows="8"
                          data-validate="{required:true}"
                          style="resize: none;"
                ><?= $block->escapeHtml($viewModel->getUserComment()) ?></textarea>
            </div>
        </div>
        <div class="field choice required">
            <input id="00N3N00000KBGOq"
                   name="00N3N00000KBGOq"
                   type="checkbox"
                   value="1"
                   data-validate="{required:true}"
                   checked>
            <label class="label" for="00N3N00000KBGOq">
                <?= $block->escapeHtml(
                    __("I declare to accept the Terms and Conditions and to have read the Privacy Policy provided pursuant to art. 13 EU Reg. 679/2016 (GDPR).")
                ) ?>
            </label>
        </div>
        <div class="field choice">
            <input id="00N3N00000KBGLS"
                   name="00N3N00000KBGLS"
                   type="checkbox"
                   value="1">
            <label class="label" for="00N3N00000KBGLS">
                <?= $block->escapeHtml(
                    __("I consent to the processing of my personal data for the sending of commercial communications and advertising by NexTouch S.p.A. by email and SMS.")
                ) ?>
            </label>
        </div>
        <div class="field choice">
            <input id="00N3N00000KBZat"
                   name="00N3N00000KBZat"
                   type="checkbox"
                   value="1">
            <label class="label" for="00N3N00000KBZat">
                <?= $block->escapeHtml(
                    __("I consent to the processing of my personal data for profiling purposes by creating a user profile in order to send personalized communications in line with my interests exclusively by NexTouch S.p.A. also through the use of electronic and automated tools.")
                ) ?>
            </label>
        </div>
        <?= $block->getChildHtml('form.additional.info') ?>
    </fieldset>
    <div class="actions-toolbar">
        <p>
            <?= $block->escapeHtml('The assistance service is active from Monday to Friday from 00:00 to 00:00.') ?><br>
            <?= $block->escapeHtml('Our operators will reply as soon as possible.') ?>
        </p>

        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                <span><?= $block->escapeHtml(__('Submit')) ?></span>
            </button>
        </div>
    </div>
</form>

<div style="margin-top: 100px">
    <?= $aboutServicesSlider->toHtml() ?>
</div>

<div style="margin-top: 100px">
    <?= $aboutBanners->toHtml() ?>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "contact-form"
            }
        }
    }
</script>
