<?php

/** @var \Magento\Sales\Block\Order\History $block */ ?>
<?php $_orders = $block->getOrders(); ?>
<?php $_elightHelper = $this->helper(Elightwalk\Core\Helper\Data::class); ?>
<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)) : ?>
    <div class="table-wrapper orders-history">
        <!-- <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= $block->escapeHtml(__('Orders')) ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="col id"><?= $block->escapeHtml(__('Order #')) ?></th>
                    <th scope="col" class="col date"><?= $block->escapeHtml(__('Date')) ?></th>
                    <?= $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col total"><?= $block->escapeHtml(__('Order Total')) ?></th>
                    <th scope="col" class="col status"><?= $block->escapeHtml(__('Status')) ?></th>
                    <th scope="col" class="col actions"><?= $block->escapeHtml(__('Action')) ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order) : ?>
                    <div id="product-description-collapsible" class="product-description">
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id">
                            <?= $block->escapeHtml($_order->getRealOrderId()) ?>
                            <div class="sub-col actions">
                                <a href="<?= $block->escapeUrl($block->getViewUrl($_order)) ?>">
                                    <span><?= $block->escapeHtml(__('View order details')) ?></span>
                                </a>
                            </div>
                        </td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra) : ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= $block->escapeHtml($_order->getStatusLabel()) ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                <a href="#" data-post='<?= /* @noEscape */
                                                        $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                                            ->getPostData($block->getReorderUrl($_order))
                                                        ?>' class="action order">
                                    <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                </a>
                            <?php endif ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table> -->
        <div class="data table table-order-items history">
            <div class="order-items order-items-col">
                <?php foreach ($_orders as $_order) : ?>
                    <div class="order-items-collapsible">
                        <div class="order-row-data">
                            <div data-role="order-placed" class="order-box">
                                <p><?= __('ORDER PLACED ON:') ?></p>
                                <span><?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?></span>
                            </div>
                            <div data-role="order-total" class="order-box">
                                <p><?= __('TOTAL:') ?></p>
                                <span><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></span>
                            </div>
                            <!-- <div data-role="order-total" class="order-box">
                            <p><?= __('SEND TO:') ?></p><br>
                            <span><?= /* @noEscape */ $_order->formatPrice($_order->getGrandTotal()) ?></span>
                        </div> -->
                            <div data-role="order-state" class="order-box">
                                <p><?= __('STATE:') ?></p>
                                <span><?= $block->escapeHtml($_order->getStatusLabel()) ?></span>
                            </div>
                        </div>
                        <div data-role="content" class="more-less-content">
                            <div class="more-less-wrapper">
                                <ul class="">
                                    <?php $items = $_order->getAllVisibleItems();
                                    $item =  array_slice($items, 0, 3);
                                    foreach ($item as $itm) : ?>
                                        <?php $_product   = $_elightHelper->getProductById($itm->getProductId()); ?>
                                        <?php $image_url  = $_elightHelper->getImageUrl($_product); ?>
                                        <li class="order-row-item">
                                            <div class="order-col">
                                                <div class="order-row-product-image">
                                                    <img src="<?php echo $image_url; ?>" border="0" alt="order-product-image" />
                                                </div>
                                            </div>
                                            <div class="order-col">
                                                <div class="order-row-product-content product-name">
                                                    <?php echo $this->escapeHtml($itm->getName()) ?>
                                                </div>
                                                <div class="order-row-product-content product-discription">
                                                    <?php echo $_product->getDescription() ?>
                                                </div>
                                                <!-- <div class="order-row-product-content">
                                                    <?php echo $this->escapeHtml('DELIVERED ON:') ?>
                                                    <?php echo $this->escapeHtml('SCHEDULED DELIVERY:') ?>
                                                    <?= /* @noEscape */ $block->formatDate($_order->getCreatedAt()) ?>
                                                </div> -->
                                            </div>
                                            <div class="order-col btn-group">
                                                <div class="order-button-more">
                                                    <?php if ($this->helper(\Magento\Sales\Helper\Reorder::class)->canReorder($_order->getEntityId())) : ?>
                                                        <a href="#" data-post='<?= /* @noEscape */
                                                                                $this->helper(\Magento\Framework\Data\Helper\PostHelper::class)
                                                                                    ->getPostData($block->getReorderUrl($_order))
                                                                                ?>' class="action order">
                                                            <span><?= $block->escapeHtml(__('Reorder')) ?></span>
                                                        </a>
                                                    <?php endif ?>
                                                </div>
                                                <!-- <div class="order-button-more">
                                                    <?php echo $this->escapeHtml('FIND OUT MORE') ?>
                                                </div>
                                                <div class="order-button">
                                                    <?php echo $this->escapeHtml('REQUEST RETURN') ?>
                                                </div>
                                                <div class="order-button">
                                                    <?php echo $this->escapeHtml('REQUEST INVOICE') ?>
                                                </div>
                                                <div class="order-button">
                                                    <?php echo $this->escapeHtml('CHANGE ADDRESS') ?>
                                                </div>
                                                <div class="order-button">
                                                    <?php echo $this->escapeHtml('CANCEL ORDER') ?>
                                                </div>
                                                <div class="order-button">
                                                    <?php echo $this->escapeHtml('CANCEL RETURN') ?>
                                                </div> -->
                                            </div>
                                        </li>
                                    <?php endforeach; ?>
                                </ul>
                            </div>
                            <div class="more-less">
                                <span class="more"> <?= __('Show more') ?></span>
                                <span class="less"> <?= __('Show less') ?></span>
                            </div>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </div>
    </div>
    <?php if ($block->getPagerHtml()) : ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else : ?>
    <div class="message info empty"><span><?= $block->escapeHtml($block->getEmptyOrdersMessage()) ?></span></div>
<?php endif ?>

<script>
    require(['jquery'], function($) {
        $(".more-less-content .more-less").on('click', function() {
            var parentMoreLess = $(this).closest('.more-less-content');

            if (parentMoreLess.hasClass('active') == false) {
                $('.table-wrapper.orders-history').addClass('active');
                $(this).parent().parent().addClass('active');
                parentMoreLess.addClass('active');
            } else {
                $('.table-wrapper.orders-history').removeClass('active');
                $(this).parent().parent().removeClass('active');
                parentMoreLess.removeClass('active');
                // $('html,body').animate({
                //     scrollTop: $(this).parent().offset().top - 200
                // }, 400);
            }
        });

        $(".order-row-data").on('click', function() {
            var parentMoreLess = $(this).parent().find('.more-less-content');

            if (parentMoreLess.hasClass('active') == false) {
                $('.table-wrapper.orders-history').addClass('active');
                $(this).parent().addClass('active');
                parentMoreLess.addClass('active');
            } else {
                $('.table-wrapper.orders-history').removeClass('active');
                $(this).parent().removeClass('active');
                parentMoreLess.removeClass('active');
                // $('html,body').animate({
                //     scrollTop: $(this).parent().offset().top - 200
                // }, 400);
            }
        });

    });
</script>
