<?php /** @var \Magento\Wishlist\Block\Catalog\Product\View\AddTo\Wishlist $block */ ?>

<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= $block->getAddToWishlistParams($block->getProduct()); ?>'
       data-action="add-to-wishlist">
        <span class="material-icons text-primary">favorite</span>
    </a>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= $block->getWishlistOptionsJson(); ?>
        }
    }
</script>
