<?php /** @var \Nextouch\Theme\Block\Catalog\Product\View\AddTo\Wishlist $block */ ?>

<?php if ($block->isWishListAllowed()) : ?>
    <a href="#"
       class="action towishlist"
       data-post='<?= $block->getPostParams(); ?>'
       data-action="add-to-wishlist">
        <?php if ($block->isInWishlist()) : ?>
            <i class="fas fa-heart fa-3x text-primary"></i>
        <?php else : ?>
            <i class="far fa-heart fa-3x text-primary"></i>
        <?php endif; ?>
    </a>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        "body": {
            "addToWishlist": <?= $block->getWishlistOptionsJson(); ?>
        }
    }
</script>
